// strings.js — все тексты интерфейса на двух языках.
// ОГЭ = ru (родной интерфейс), ЕГЭ = en (полное погружение, уровень B1).
// Активный набор выбирается в exam.js по exam.lang.

// Склонение русского числительного: forms = [1, 2-4, 5-0]. Локально, чтобы strings.js
// не зависел от exam.js (там есть plural, но импорт сюда дал бы цикл).
function pluralRu(n, forms) {
  const m10 = n % 10, m100 = n % 100;
  if (m10 === 1 && m100 !== 11) return forms[0];
  if (m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14)) return forms[1];
  return forms[2];
}

export const STRINGS = {
  ru: {
    // splash
    brandline: 'Speak & Smile · Тренажёр ОГЭ',
    greetHi: 'Привет! Я Спики 👋', greetQ: 'Как тебя зовут?',
    namePlaceholder: 'Твоё имя', go: 'Поехали!',
    offlineNote: 'Всё работает оффлайн. Прогресс хранится на твоём устройстве — без аккаунтов.',
    // nav
    navHome: 'Главная', navProgress: 'Прогресс', navRewards: 'Награды',
    // home
    welcomeBack: 'С возвращением', today: 'Сегодня', week: 'За неделю', lvl: 'Ур.',
    toRank: (r, n) => `до «${r}»: ${n} XP`, maxRank: 'максимальное звание',
    empty: 'пока пусто',
    goalTitle: 'Цель дня', goalDone: (s) => `Готово на сегодня — ${s}`, goalIdle: 'Сделай хотя бы 1 раунд',
    packTitle: '🦸 Пак недели', packOf: (n, tot) => `${n} из ${tot}`,
    packNote: 'Выполни недельную норму в каждом разделе — собери пак и стань Героем',
    sectionsTitle: 'Разделы', myProgress: 'Мой прогресс', rewards: 'Награды',
    soonTitle: 'Аудирование', soonMeta: 'появится в следующем обновлении', soon: 'Скоро',
    soonScreenTitle: 'Скоро', soonScreenText: 'Этот раздел в разработке — добавим в одном из следующих обновлений.',
    // reading (чтение)
    reading: {
      pick: 'Выбери тип задания',
      tfTitle: 'Верно · Неверно · Не сказано', tfSub: '28 текстов · по 7 утверждений',
      matchTitle: 'Текст ↔ вопрос', matchSub: '38 заданий · тексты A–F',
      readFirst: 'Прочитай текст и оцени каждое утверждение',
      matchInstr: 'Подбери к каждому тексту A–F нужный вопрос',
      questionsTitle: 'Вопросы',
      tf: ['Верно', 'Неверно', 'Не сказано'],
      pickQ: '—',
      correctNum: (n) => 'Верно: ' + n,
      nextText: 'Другой текст',
      why: 'Почему', evidenceLabel: 'В тексте',
      notStatedNote: 'В тексте об этом не говорится.',
    },
    readingEge: {
      pick: 'Выбери тип задания',
      headingsTitle: 'Подбор заголовков', headingsSub: '56 заданий · 7 текстов ↔ 8 заголовков',
      gapsTitle: 'Вставка частей', gapsSub: '57 заданий · вставь пропущенные части',
      mcTitle: 'Выбор ответа', mcSub: '51 текст · по несколько вопросов',
      headingsInstr: 'Подбери к каждому тексту (A–G) заголовок. Один лишний.',
      gapsInstr: 'Заполни каждый пропуск (A–F) нужной частью. Одна лишняя.',
      mcInstr: 'Прочитай текст и выбери правильный ответ на каждый вопрос.',
      headingsLabel: 'Заголовки', partsLabel: 'Части', questionsTitle: 'Вопросы',
      readFirst: 'Читай внимательно',
      pickN: '—',
      correctNum: (n) => 'Верно: ' + n,
      nextText: 'Другое задание',
      why: 'Почему',
    },
    // listening (аудирование — аутентичное аудио ФИПИ + проверка по ключу)
    listening: {
      pickVariant: 'Выбери вариант',
      variant: (n) => 'Вариант ' + n,
      variantSub: '11 заданий · аудио ФИПИ',
      listenHint: 'Послушай запись (на экзамене она звучит дважды) и выполни задания',
      audioErr: 'Не удалось загрузить аудио — нужен интернет. Попробуй ещё раз позже.',
      matchInstr: 'Сопоставь каждого говорящего (A–E) с рубрикой. Одна рубрика лишняя.',
      rubricsLabel: 'Рубрики',
      chooseInstr: 'Выбери правильный ответ',
      fillHint: 'Впиши одно слово (без артикля; число — словом)',
      transcriptTitle: 'Скрипт записи',
      transcriptHint: 'Нажми на предложение, чтобы переслушать этот фрагмент',
      source: '🔊 В записи',
      correctIs: (a) => 'Верно: ' + a,
      speaker: 'Говорящий',
      pick: '—',
      checkAll: 'Проверить',
      nextText: 'Другой вариант',
      byKesTitle: 'По кодификатору',
      kes: { '1.2.1': 'Основное содержание', '1.2.2': 'Запрашиваемая информация', '1.2.3': 'Полное понимание' },
      doneScore: (c, tot) => `✓ Пройдено · ${c}/${tot} б.`,
      tasksPts: (n, pts) => `${n} ${pluralRu(n, ['задание', 'задания', 'заданий'])} · ${pts} ${pluralRu(pts, ['балл', 'балла', 'баллов'])}`,
      maxPts: (pts) => `максимум за раздел — ${pts} ${pluralRu(pts, ['балл', 'балла', 'баллов'])}`,
      pointsWord: (pts) => pluralRu(pts, ['балл', 'балла', 'баллов']),
      tfns: ['Верно', 'Неверно', 'Не сказано'],
      tfnsInstr: 'Верно / Неверно / Не сказано — отметь каждое утверждение',
      cat: { match: 'Соответствие говорящих', tf: 'Верно · Неверно · Не сказано', mc: 'Выбор ответа' },
      catShort: { match: 'соответствие', tf: 'верно/неверно', mc: 'выбор' },
      allVariants: 'Варианты',
    },
    // speaking (говорение — Шаг 1: диктофон + эталоны + само-оценка)
    speaking: {
      pick: 'Выбери тип задания',
      taskCount: (n) => `${n} ${pluralRu(n, ['задание', 'задания', 'заданий'])}`,
      catRead: 'Задание 1 · Чтение вслух',
      catSurvey: 'Задание 2 · Телефонный опрос',
      catMono: 'Задание 3 · Монолог',
      readInstr: 'Прочитай текст про себя (1,5 мин), затем вслух (до 2 мин). Запиши себя и сравни с эталоном.',
      surveyInstr: 'Телефонный опрос: послушай 6 вопросов и ответь полными предложениями (по 40 сек на вопрос). Запиши себя.',
      surveyPlay: 'Включи запись с вопросами',
      monoInstr: (topic) => `Монолог на тему «${topic}» — 10–12 предложений, до 2 минут. Говори связно по плану.`,
      planTitle: 'План (раскрой все пункты):',
      yourTurn: '🎤 Теперь запиши свой ответ:',
      listenModel: 'Послушать эталон',
      ttsPause: 'Пауза', ttsResume: 'Продолжить', ttsStop: 'Стоп',
      sampleTitle: 'Образец ответа',
      surveyQs: 'Вопросы и образцы ответов',
      listenNative: 'Послушать носителя по теме',
      randomTask: 'Случайное задание',
      surveyCard: (th) => 'Опрос: ' + th,
      doneOf: (d, n) => `${d}/${n} выполнено`,
      catLabel: (k) => ({ read: 'Чтение вслух', survey: 'Телефонный опрос', monologue: 'Монолог' }[k] || ''),
      recStart: '🎤 Записать', recStop: '⏹ Стоп', recAgain: '↺ Перезаписать',
      recOn: 'Идёт запись… говори', micErr: 'Нет доступа к микрофону — разреши его в браузере',
      critTitle: 'Сверься с критериями:',
      critRead: ['Прочитал(а) весь текст без пропусков', 'Соблюдал(а) интонацию (паузы, вопросы)', 'Не больше 2 ошибок в словах', 'Читал(а) бегло, без долгих запинок'],
      critSurvey: ['Ответил(а) на все 6 вопросов', 'Каждый ответ — полное предложение (не одно слово)', 'Успел(а) за 40 секунд на вопрос', 'Ответы по теме вопроса'],
      critMono: ['Раскрыл(а) все 4 пункта плана', '10–12 предложений', 'Связно: вступление, связки, вывод', 'Уложился(ась) в 2 минуты, без долгих пауз'],
      aiCheck: 'Проверить с ИИ',
      aiNoRec: 'Сначала запиши свой ответ',
      aiRecognizing: 'Распознаю речь…',
      aiEvaluating: 'Оцениваю по критериям…',
      aiErr: 'Не получилось:',
      aiEmpty: 'Речь не распознана — запиши ещё раз, чётче и ближе к микрофону.',
      aiTranscript: 'Что распознал ИИ',
      aiNote: 'Оценка ориентировочная: ИИ судит по распознанному тексту (содержание, грамматика, полнота). Произношение и интонацию лучше проверить с преподавателем.',
      doneBtn: 'Готово, потренировался(ась)',
      donePraise: (name) => `${name}, отличная тренировка речи! 🎤`,
      doneSub: 'Само-оценка по критериям — половина успеха. Скоро добавим проверку ИИ.',
      more: 'Ещё задание',
    },
    // mock (пробный экзамен — собранный вариант с жёстким таймером)
    mock: {
      loading: 'Готовлю варианты…',
      title: 'Пробный экзамен',
      pickVariant: 'Выбери вариант',
      variant: (n) => 'Вариант ' + n,
      ptsShort: 'б',
      notTaken: 'ещё не проходил(а)',
      lastResult: (s, m) => `прошлый раз: ${s} из ${m}`,
      pointA: 'Точка А',
      pointASub: 'Пройди первый пробник — зафиксируем старт, дальше будем видеть рост.',
      heroTitle: 'Пробный экзамен',
      heroSub: 'Целый вариант как на ФИПИ, с таймером. Без подсказок — всё по-настоящему.',
      rules: [
        'Жёсткий таймер на всю работу — на нуле всё сдаётся автоматически.',
        'Без подсказок, проверки и скрипта — баллы будут в конце.',
        'Письмо проверит ИИ (нужен интернет), остальное — по ключам.',
      ],
      startTitle: (n) => `Вариант ${n} — начать?`,
      startWarn: (min) => `Таймер ${min} минут пойдёт сразу и не остановится. Найди тихое место.`,
      startBtn: 'Начать',
      sectionOf: (a, b) => `Раздел ${a} из ${b}`,
      nextSection: 'Следующий раздел →',
      finishBtn: 'Завершить и узнать баллы',
      finishTitle: 'Завершить экзамен?',
      finishWarn: 'Ответы примутся как есть, изменить будет нельзя.',
      keepGoing: 'Ещё подумаю',
      listenHint: 'Включи запись. В экзамене аудио звучит дважды — слушай внимательно.',
      answerPh: 'Ответ',
      rubricsLabel: 'Рубрики:',
      matchTitle: 'Установи соответствие текстов и вопросов:',
      gapsTitle: 'Заполни пропуски частями предложений:',
      partsLabel: 'Части:',
      tfTitle: 'Отметь для каждого утверждения:',
      tfLabels: ['Верно', 'Неверно', 'Не сказано'],
      writePh: 'Пиши ответ здесь…',
      writeInstr: 'Напиши личное письмо 100–120 слов: ответь на вопросы друга, соблюди формат.',
      writeWords: (a, b) => `Объём: ${a}–${b} слов. Соблюди формат.`,
      words: (n) => `${n} ${pluralRu(n, ['слово', 'слова', 'слов'])}`,
      scoring: 'Считаю баллы…',
      timeUp: '⏱ Время вышло — приняли что успел(а)',
      pointsScored: (p) => `это ${p}% письменной части`,
      writtenPartNote: 'Это письменная часть (макс ≈ 53 б). Говорение добавляет ещё до 15 б.',
      pointsFull: (p) => `это ${p}% от 68 баллов`,
      fullPartNote: 'Полный экзамен ОГЭ: письменная + устная части (макс 68).',
      testProj: (n) => `≈ ${n} / 100 тестовых`,
      testProjNote: 'Прогноз: тот же уровень на устной части. Первичный → тестовый по таблице ФИПИ.',
      gradeProj: (g) => `Прогноз отметки: ${g}`,
      gradeProjNote: 'Прогноз по 5-балльной шкале ОГЭ (с учётом устной части на том же уровне).',
      gradeReal: (g) => `Отметка: ${g}`,
      gradeRealNote: 'Отметка по 5-балльной шкале ОГЭ (письменная + устная части).',
      speakHint: 'Запиши ответ на каждое задание. Речь оценит ИИ в конце экзамена.',
      spkRead: 'Чтение вслух', spkSurvey: 'Телефонный опрос', spkMono: 'Монолог',
      spkRecorded: '✓ записано',
      scoringSpeaking: (d, n) => `Проверяю устную часть… (${d}/${n})`,
      speakResult: 'Говорение — оценка ИИ',
      speakPending: 'Устную часть не удалось проверить (нет интернета) — она не вошла в баллы.',
      bySection: 'По разделам',
      byKes: 'По кодификатору (КЭС)',
      writingResult: 'Письмо — оценка ИИ',
      backToList: 'К списку вариантов',
      writePending: 'Письмо не удалось проверить (нет интернета) — оно не вошло в баллы.',
      writeEmpty: 'Письмо не написано — 0 баллов за раздел.',
    },
    mockPrompt: {
      firstTitle: 'Зафиксируй точку А',
      firstText: 'Пройди первый пробный экзамен — увидим твой старт, а дальше будем отслеживать рост.',
      dueTitle: 'Пора пройти пробный',
      dueText: 'Прошёл месяц с прошлого пробника. Проверь форму на целом варианте с таймером.',
      weeklyText: 'До экзамена меньше месяца — пробники теперь раз в неделю. Время для нового!',
      go: 'Пройти пробный',
      later: 'Позже',
    },
    // vocab (лексика — тема недели + флэшкарты/SRS)
    vocab: {
      sub: 'Тема недели · 15 слов в день',
      dailyTitle: 'Норма дня',
      dailyDone: (g) => `Норма выполнена — ${g} слов 🎉`,
      dailyLeft: (c, g) => `${c} из ${g} слов сегодня`,
      startDaily: 'Тренировать слова',
      practiceMore: 'Ещё карточки',
      dueNote: (n, w) => `${n} ${w} к повторению`,
      dueNone: 'Новые слова из темы недели',
      learning: 'Тема недели: ',
      learningSub: 'Новые слова берём отсюда; повторение — вперемешку',
      pickTheme: 'Выбрать тему недели',
      searchPlaceholder: 'Найти слово или фразу…',
      searchEmpty: 'Ничего не найдено',
      searchCount: (n) => `найдено: ${n}`,
      searchTitle: 'Словарь', searchBtn: 'Словарь',
      learnedOf: (a, b) => `освоено ${a} из ${b}`,
      inProgress: (n) => `в работе ${n}`,
      tapToFlip: 'Нажми, чтобы увидеть перевод',
      dontKnow: 'Не помню',
      know: 'Помню',
      mNew: 'Новое слово', mPreview: 'Знакомство', mTrain: 'Тренировка',
      mChoose: 'Выбери перевод', mCloze: 'Впиши пропущенное слово', mType: 'Впечатай по-английски',
      next: 'Дальше →', correct: '✓ Верно!', wrongIs: (a) => '✗ Правильно: ' + a,
      typePlaceholder: 'впиши по-английски…', hintRu: (ru) => 'подсказка: ' + ru,
      finaleCardTitle: (th) => 'Тема «' + th + '» освоена! 🏆',
      finaleCardSub: 'Финал недели: закрепи письмом и эссе',
      finaleTitle: 'Финал недели',
      finaleSub: (th) => 'Тема «' + th + '» — закрепи её в письменной части',
      finaleWrite: (sec) => sec + ' по теме',
      finalePickNew: '🔄 Выбрать новую тему',
      finaleNoTasks: 'По этой теме заданий письма пока нет',
      finaleCeleb: 'Тема освоена! 🏆',
      themeWeekLabel: (th) => 'По теме недели: ' + th,
      finaleDoneBadge: '🏆 пройдена',
      dayClosed: 'Норма дня по лексике закрыта! 🎉',
      keepGoing: 'Так держать!',
      toThemes: 'К темам',
    },
    // drill
    loadingTasks: 'Загружаю задания…', allTopics: 'Все темы',
    allTopicsSub: 'Случайный раунд из 15 заданий', byCodifier: 'Темы по кодификатору',
    mistakes: 'Работа над ошибками', mistakesSub: (n, w) => `${n} ${w} на повторение`,
    tasksWord: ['задание', 'задания', 'заданий'], varWord: ['вариант', 'варианта', 'вариантов'], roundsWord: ['раунд', 'раунда', 'раундов'], streakLabel: 'серия',
    topicsWord: ['тема', 'темы', 'тем'], whyCorrect: 'Верно!', whyCheck: 'Сверь с правильным вариантом выше.',
    enterAnswer: 'Введи ответ', check: 'Проверить', next: 'Дальше', finish: 'Завершить раунд',
    why: 'Почему', correctIs: (k) => 'Правильно: ' + k, baseWord: 'Опорное слово',
    more15: 'Ещё раунд', otherTopic: 'Другая тема', toHome: 'На главную',
    rStreak: 'Серия', rXp: 'Опыт', rPack: 'Пак', rFreeze: 'Заморозка', freezeSaved: 'спасла серию',
    dayWord: (s) => s === 1 ? 'день' : 'дн.',
    praiseHigh: 'отличный темп!', praiseMid: 'хороший результат', praiseLow: 'есть над чем поработать',
    accLine: (acc, praise) => `${acc}% верных ответов · ${praise}`,
    // writing (ОГЭ — одно письмо)
    wLoading: 'Загружаю темы писем…', wPickSub: 'Выбери письмо друга — ответь 100–120 слов', wAllLetters: 'Остальные',
    wLetterFrom: (n) => 'Письмо от друга — ' + n, wFrom: (n) => 'Письмо от ' + n,
    wCheck: 'Проверить письмо', wRecheck: 'Проверить заново',
    wFrame: 'Каркас (опора)', wIdeas: 'Идеи: о чём писать', wConnectors: 'Связки',
    wVerdictDefault: 'Проверено по критериям К1–К4.',
    wErrorsTitle: 'Ошибки: было → стало', wCorrectedTitle: 'Исправленный вариант',
    wMyWorks: 'Мои работы', wWorksSub: (n) => `сохранено: ${n}`,
    wWorksEmpty: 'Здесь будут твои проверенные работы — пиши и возвращайся перечитать перед экзаменом.',
    wYourText: 'Твой ответ', wTaskPrompt: 'Задание',
    wWords: (n, w) => `${n} ${w} · 100–120`, wordsWord: ['слово', 'слова', 'слов'],
    wErrShort: 'Напиши письмо (хотя бы несколько предложений).',
    wErrServer: (s) => 'Ошибка проверки: ' + s,
    // progress
    progTitle: 'Мой прогресс', bySection: 'По разделам',
    solved: (a, c) => `решено ${a} · верно ${c}`, noSolved: 'пока нет решённых заданий',
    progDone: (d, m) => `пройдено ${d} из ${m}`,
    avgTitle: 'Средний балл за письма', avgSub: (n) => `проверено писем: ${n}`, avgCrit: 'по критериям К1–К4',
    achTitle: 'Достижения', changeName: 'Изменить имя', reset: 'Сбросить',
    resetConfirm: 'Сбросить весь прогресс на этом устройстве?',
    soundOn: '🔊 Звук: вкл', soundOff: '🔇 Звук: выкл',
    heroWord: ['герой', 'героя', 'героев'],
    // rewards / perks
    tokensLabel: (n, w) => `${w} за работу`, tokenWord: ['жетон', 'жетона', 'жетонов'],
    perksSub: 'Привилегии у учителя. Получи бейдж и покажи его на уроке.',
    skinsTitle: 'Образы XP-полосы', redeemedTitle: 'Использованные',
    skinEquipped: 'Надето', skinEquip: 'Надеть',
    skinOn: '✅ Надет сейчас', skinOpen: '✅ Открыт', perkEnough: '✅ Жетонов хватает', perkNeed: (n) => '🎟 Нужно ещё ' + n,
    levelsTitle: 'Уровни и звания', levelsHow: 'XP копится за занятия: +10 за каждый верный ответ, +30 за идеальный раунд (без ошибок). Больше XP — выше звание. Твой уровень подсвечен.',
    ptsSpend: (n) => 'Спишется: ' + n + ' 🎟', ptsRedeem: 'Обменять', perkChoose: 'Выбрать',
    // Онбординг: дата экзамена
    months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
    examWhenTitle: (exam) => 'Когда сдаёшь ' + exam + '?',
    examWhenSub: 'Поставлю счётчик на главной. Дату можно изменить позже.',
    examMonthLabel: 'Месяц', examYearLabel: 'Год', examNext: 'Дальше →', examSkip: 'Пока не знаю',
    // Счётчик на главной
    countdownTitle: 'До экзамена',
    countdownFuture: (w, exam) => '≈ ' + w + ' ' + pluralRu(w, ['неделя', 'недели', 'недель']) + ' до ' + exam,
    countdownDays: (d, exam) => d + ' ' + pluralRu(d, ['день', 'дня', 'дней']) + ' до ' + exam,
    countdownThisMonth: (exam) => exam + ' уже в этом месяце 💪',
    countdownSetTitle: 'Когда экзамен?',
    countdownSetPrompt: 'Поставь дату — включу счётчик',
    // Недельный план подготовки
    planCardTitle: 'План недели',
    planToCover: (n) => '~' + n + ' ' + pluralRu(n, ['задание', 'задания', 'заданий']) + ' в неделю',
    planPerDay: (m) => '≈ ' + m + ' в день',
    planMiniSec: (name, n) => name + ' ' + n,
    planCardSub: 'чтобы освоить всё к экзамену',
    planMinCardSub: 'весь объём не успеть — держим минимум',
    planMinShort: (n) => 'минимум ~' + n + '/нед: все темы + слова',
    planDoneCard: 'Весь объём пройден! 🎉 Повторяй и закрепляй.',
    planTitle: 'План подготовки',
    planWeeksLeft: (w) => 'До экзамена ' + w + ' ' + pluralRu(w, ['неделя', 'недели', 'недель']),
    planSummary: (n, m) => '~' + n + ' заданий в неделю · ≈ ' + m + ' в день',
    planMinBanner: 'Времени мало, чтобы освоить всё. Сначала пройди КАЖДУЮ тему хотя бы по 5 заданий и держи 15 слов в день — так закроешь все темы. Останется время — добивай до короны.',
    planSecLine: (done, tot) => 'освоено ' + done + ' из ' + tot + ' тем',
    planSecRem: (r, w) => '~' + r + ' · ' + w + '/нед',
    planSecDone: '✅ всё освоено',
    planTopicsHdr: 'Что осталось по темам',
    planTopicLeft: (k) => 'осталось ' + k,
    planVocabTitle: 'Лексика',
    planVocabLine: (l, tot) => '15 слов/день · освоено ' + l + ' из ' + tot,
    planAllDone: 'Весь банк пройден — отличная работа! Повторяй и закрепляй слабые темы.',
    readFmt: { '1.3.1': 'Подбор заголовков', '1.3.2': 'Вставка частей', '1.3.3': 'Множественный выбор' },
    planGoals: {
      full: { name: 'Весь банк', desc: 'прорешать все вопросы' },
      master: { name: 'Освоить все темы', desc: 'каждую тему до короны' },
      light: { name: 'Все темы по разу', desc: 'быстрый проход по всем темам' },
    },
    planMark: { ok: '✅', tight: '⚠️', hard: '🔒', done: '🎉' },
    planMarkText: { ok: 'реально', tight: 'интенсивно', hard: 'не успеть', done: 'пройдено' },
    planChooseHdr: 'Твоя цель',
    planRecommended: 'рекомендуем',
    planGoalCardSub: (name, day) => name + ' · ' + day,
    planHardHint: 'За оставшееся время эту цель не взять при обычном темпе — выбери полегче или поднажми.',
    // Советы Спики по разделу
    tipsTitle: (sec) => sec + ' · советы Спики',
    tipFormat: '📋 Формат', tipTime: '⏱ Время', tipHow: '✅ Как делать', tipMistakes: '⚠️ Частые ошибки',
    // Рассказ о формате (карточки-слайды). Числа: всего 68, порог 29, письмо 10 (проверено); время — из памяток.
    examIntro: [
      { img: './assets/spiky-talk.png', title: 'Что такое ОГЭ', text: 'Экзамен по английскому — это две части.\nПисьменная (≈2 часа): аудирование, чтение, грамматика и лексика, письмо.\nУстная — говорение (≈15 минут).\nВсего 68 баллов: на тройку хватит 29, на пятёрку — от 58.' },
      { img: './assets/spiky-check.png', title: 'Письменная часть', text: '4 раздела, время между ними распределяешь сам:\n1) Аудирование (≈30 мин) — слушаешь и отвечаешь.\n2) Чтение (≈25–30 мин).\n3) Грамматика и лексика (≈15–20 мин).\n4) Письмо (≈20–25 мин).' },
      { img: './assets/spiky-idea.png', title: 'Письмо и говорение', text: 'Письмо (задание 35) — личное письмо другу: 100–120 слов, 10 баллов.\nВажно: меньше 90 слов — ноль за всё задание!\nГоворение — отдельная часть: читаешь текст вслух и отвечаешь на вопросы.' },
      { img: './assets/spiky-thumb.png', title: 'Главное — тренировка', text: 'Здесь ты прокачаешь каждый раздел: грамматику, словообразование, чтение, письмо и лексику.\nВ каждом разделе Спики подскажет, как делать задание и сколько тратить времени.\nПоехали! 💪' },
    ],
    rewSub: 'Скины XP-полосы. Открываются за уровни и собранных героев.',
    badgeShow: '👀 Покажи этот экран учителю', badgeDone: 'Готово',
    // celebration moments
    celHeroT: 'ГЕРОЙ!', celLevelT: (lvl, t) => 'Уровень ' + lvl + ' · ' + t,
    celStreakT: (n) => n + ' дней подряд!', celFreezeT: 'Заморозка получена',
    celTokenT: (n, w) => '+' + n + ' ' + w, celTokenText: (name) => `Жетон в копилку, ${name}. Обменяй на привилегию у учителя 🎟`,
    celAchText: (desc, phrase) => 'Достижение «' + desc + '». ' + phrase,
    celNext: 'Дальше →', celClaim: 'Забрать!',
    achGot: '✅ Получено', achLocked: '🔒 Ещё не получено', modalClose: 'Понятно',
    friend: 'друг',
    // названия и подписи разделов (по id)
    sections: { vocab: 'Тематический словарь', grammar: 'Грамматика', wordform: 'Словообразование', reading: 'Чтение', listening: 'Аудирование', writing: 'Письмо', speaking: 'Говорение', mock: 'Пробный экзамен', lexis: 'Лексика', email: 'Письмо (e-mail)', essay: 'Эссе' },
    sectionMeta: { vocab: 'тема недели · 15 слов в день', grammar: '661 задание · 15 тем', wordform: '437 заданий · 7 тем', reading: '28 текстов + 38 заданий', listening: '19 вариантов · аудио ФИПИ', writing: 'задание 35 · К1–К4', speaking: '91 задание · диктофон + эталоны', mock: '19 вариантов · таймер · баллы', lexis: '728 заданий', email: 'задание 37 · К1–К3', essay: 'задание 38 · К1–К5' },
    // звания / скины / ачивки / привилегии
    ranks: ['Новичок', 'Стажёр', 'Знаток', 'Профи', 'Мастер', 'Легенда'],
    skins: {
      aurora: { name: 'Аврора', desc: 'Фиолетовый → медовый', need: 'доступно сразу', how: 'Скин — это цвет твоей XP-полосы вверху экрана. «Аврора» (фиолетовый → медовый) доступна сразу, надевается одним тапом.' },
      sunset: { name: 'Закат', desc: 'Малина → оранжевый', need: 'Уровень 2', how: 'Скин раскрашивает XP-полосу. «Закат» (малина → оранжевый) открывается на 2-м уровне — копи XP за верные ответы.' },
      grape: { name: 'Виноград', desc: 'Глубокий фиолет', need: 'Уровень 4', how: 'Скин раскрашивает XP-полосу. «Виноград» (глубокий фиолет) открывается на 4-м уровне.' },
      honeycomb: { name: 'Медовый', desc: 'Тёплый медовый', need: '2 героя', how: 'Скин раскрашивает XP-полосу. «Медовый» открывается, когда станешь Героем 2 раза (соберёшь пак дважды).' },
      guru: { name: 'Гуру', desc: 'Весь спектр S&S', need: 'Звание «Легенда»', how: 'Скин раскрашивает XP-полосу. «Гуру» (весь спектр Speak & Smile) открывается с высшим званием «Легенда» — это 6-й уровень.' },
    },
    ach: {
      first: { title: 'Первый шаг', desc: 'Первый раунд', how: 'Реши свой самый первый раунд — заработай первые XP. Лиха беда начало!' },
      perfect: { title: 'Идеал', desc: 'Идеальный раунд', how: 'Пройди целый раунд без единой ошибки. За идеальный раунд ещё и заморозка серии в подарок.', rep: (n) => 'Идеальных раундов: ' + n + ' · +' + n + ' 🧊' },
      hero: { title: 'Герой', desc: 'Собери пак', how: 'Собери весь «пак недели» — закрой все разделы за период. За пак дают жетон 🎟 на привилегию у учителя.', rep: (n) => 'Собрано паков: ' + n + ' · +' + n + ' 🎟' },
      hundred: { title: 'Сотка', desc: '100 заданий решено', how: 'Реши 100 заданий всего (по любым разделам). Счётчик копится сам.' },
      week: { title: 'Неделя в деле', desc: 'Серия 7 дней', how: 'Занимайся 7 дней подряд — доведи серию 🔥 до семёрки. Каждый день закрывай норму лексики, чтобы серия росла. Дойдёшь до 7/14/30/50/100 — +2 🎟; порвётся и снова доберёшься — жетоны дадут опять.', rep: (n) => 'Твой рекорд серии: ' + n + ' дн.' },
      gold: { title: 'Мастер темы', desc: 'Золотая корона', how: 'Доведи любую тему до золотой короны 👑 — много решённых заданий с высокой точностью.', rep: (n) => 'Золотых корон: ' + n },
      fivehundred: { title: 'Полтысячи', desc: '500 заданий решено', how: 'Реши 500 заданий всего. Это уже серьёзный объём — настоящая прокачка.' },
      frosty: { title: 'Запасливый', desc: '3 заморозки в запасе', how: 'Накопи 3 заморозки серии 🧊 (по одной за каждый идеальный раунд). Заморозка прикрывает пропущенный день.' },
    },
    perks: {
      hint: { title: 'Подсказка на тесте', desc: 'Право на одну подсказку во время теста', how: 'Настоящая привилегия у преподавателя: одна подсказка во время теста. Стоит 2 🎟. Обменяешь — получишь код, покажи его учителю. Жетоны капают за собранные паки (Герой) и вехи серии.' },
      nohw: { title: 'Урок без ДЗ', desc: 'Прийти на урок без домашнего задания', how: 'Настоящая привилегия: прийти на урок без домашки. Стоит 4 🎟. Обменяешь — получишь код для учителя. Жетоны зарабатываешь за паки и серию.' },
      points: { title: 'Баллы к тесту', titleN: (n) => '+' + n + ' ' + pluralRu(n, ['балл', 'балла', 'баллов']) + ' к тесту', desc: 'Обменяй жетоны на баллы: 1 🎟 = +1 балл', how: 'Настоящий бонус у преподавателя: добавь баллы к результату теста. 1 жетон = +1 балл, можно от 1 до 10 за тест (сколько хватит жетонов). Выбираешь, сколько потратить, — получишь код «+N баллов», покажи учителю.', chooseHelp: (bal) => '1 жетон = +1 балл к тесту. У тебя ' + bal + ' 🎟. Выбери, сколько добавить (до 10).', chooseBig: (n) => '+' + n, badgeShow: '👀 Покажи код учителю — он добавит баллы к тесту' },
      coins: { title: 'Монеты «Твоя школа»', titleN: (n) => (n * 5) + ' ' + pluralRu(n * 5, ['монета', 'монеты', 'монет']) + ' «Твоя школа»', desc: 'Обменяй жетоны на монеты: 1 🎟 = 5 монет', how: 'Настоящий обмен: переведи жетоны в монеты приложения «Твоя школа» — их тратят на реальные покупки в школьном магазине. 1 жетон = 5 монет. Выбираешь, сколько жетонов обменять, — получишь код, покажи учителю, чтобы он начислил монеты.', chooseHelp: (bal) => '1 жетон = 5 монет «Твоя школа». У тебя ' + bal + ' 🎟. Выбери, сколько обменять.', chooseBig: (n) => (n * 5) + ' монет', badgeShow: '👀 Покажи код учителю — он начислит монеты в «Твоя школа»' },
    },
    voice: {
      homeIdle: ['{name}, серия ждёт. Не сливайся 😎', '{name}, твой ход. 1 раунд — погнали.', '{name}, один раунд — и ты в деле.', 'Ну что, {name}, докажем?'],
      homeDone: ['Цель закрыта, {name}. Но кто сказал стоп? 😏', '{name}, день взят. Ещё круг?', '{name}, норма закрыта. Добавки? 😏'],
      high: ['{score}, {name}. Чисто 😎', '{name}, красиво. Слабо все 15? 😉', 'Сильно, {name}. Так держать.', '{score} — {name} в ударе 🔥'],
      mid: ['{score}, {name}. Норм, но ты можешь чище.', 'Идём, {name}. Дожми в следующем.', '{name}, крепко. Ещё чуть-чуть — и чисто.'],
      low: ['{name}, это не твой потолок. Реванш?', 'Бывает, {name}. Разбор уже помог — погнали ещё.', '{name}, не считается. Ещё раунд — и покажем класс.'],
      hero: ['{name} — ГЕРОЙ. Весь пак твой 🦸', 'Полный пак, {name}. Уважение 🤝', '{name}, пак собран целиком. Красава 🦸'],
      celHero: ['Весь пак за один заход, {name}. Это уровень 🦸', '{name}, ты взял(а) весь пак. Огонь!', 'Грамматика, словообразование, письмо — всё твоё, {name}.'],
      celLevel: ['Растёшь на глазах, {name}. Дальше — выше!', 'Новая ступень взята, {name}. Так и надо 💪', '{name}, уровень апнут. ОГЭ всё ближе.'],
      celStreak: ['Привычка побеждать, {name}. Не отпускай 🔥', '{name}, столько дней подряд — характер!', 'Каждый день в деле, {name}. Это и есть результат.'],
      celFreeze: ['Заморозка в кармане, {name}. Один пропуск теперь не страшен 🧊', '{name}, серия под защитой. Можно выдохнуть.'],
      celAch: ['Новое достижение, {name}! Коллекция растёт 🏅', '{name}, есть новая ачивка. Так держать!', 'Ещё один значок твой, {name}. Красиво.'],
    },
  },

  en: {
    // splash
    brandline: 'Speak & Smile · EGE Trainer',
    greetHi: "Hi! I'm Speaky 👋", greetQ: "What's your name?",
    namePlaceholder: 'Your name', go: "Let's go!",
    offlineNote: 'Everything works offline. Your progress stays on your device — no accounts.',
    // nav
    navHome: 'Home', navProgress: 'Progress', navRewards: 'Rewards',
    // home
    welcomeBack: 'Welcome back', today: 'Today', week: 'This week', lvl: 'Lv.',
    toRank: (r, n) => `to "${r}": ${n} XP`, maxRank: 'top rank reached',
    empty: 'nothing yet',
    goalTitle: 'Daily goal', goalDone: (s) => `Done for today — ${s}`, goalIdle: 'Do at least one round',
    packTitle: '🦸 Weekly pack', packOf: (n, tot) => `${n} of ${tot}`,
    packNote: 'Hit the weekly target in every section — collect the pack and become a Hero',
    sectionsTitle: 'Sections', myProgress: 'My progress', rewards: 'Rewards',
    soonTitle: 'Reading · Listening', soonMeta: 'coming in the next update', soon: 'Soon',
    soonScreenTitle: 'Coming soon', soonScreenText: 'This section is under development — it will appear in a future update.',
    // reading
    reading: {
      pick: 'Choose a task type',
      tfTitle: 'True · False · Not stated', tfSub: '28 texts · 7 statements each',
      matchTitle: 'Text ↔ question', matchSub: '38 tasks · texts A–F',
      readFirst: 'Read the text and judge each statement',
      matchInstr: 'Match each text A–F to the right question',
      questionsTitle: 'Questions',
      tf: ['True', 'False', 'Not stated'],
      pickQ: '—',
      correctNum: (n) => 'Correct: ' + n,
      nextText: 'Another text',
      why: 'Why', evidenceLabel: 'In the text',
      notStatedNote: 'This is not mentioned in the text.',
    },
    readingEge: {
      pick: 'Choose a task type',
      headingsTitle: 'Match the headings', headingsSub: '56 tasks · 7 texts ↔ 8 headings',
      gapsTitle: 'Gapped text', gapsSub: '57 tasks · insert the missing parts',
      mcTitle: 'Multiple choice', mcSub: '51 texts · several questions each',
      headingsInstr: 'Match each text (A–G) to a heading. One heading is extra.',
      gapsInstr: 'Fill each gap (A–F) with the right part. One part is extra.',
      mcInstr: 'Read the text and choose the best answer for each question.',
      headingsLabel: 'Headings', partsLabel: 'Parts', questionsTitle: 'Questions',
      readFirst: 'Read carefully',
      pickN: '—',
      correctNum: (n) => 'Correct: ' + n,
      nextText: 'Another task',
      why: 'Why',
    },
    listening: {
      pickVariant: 'Choose a variant',
      variant: (n) => 'Variant ' + n,
      variantSub: 'multiple choice · FIPI audio',
      listenHint: 'Listen to the recording (in the exam it plays twice) and do the tasks',
      audioErr: 'Could not load the audio — you need an internet connection. Try again later.',
      matchInstr: 'Match each speaker (A–E) to a statement. One statement is extra.',
      rubricsLabel: 'Statements',
      chooseInstr: 'Choose the correct answer',
      fillHint: 'Type one word (no article; spell numbers out)',
      transcriptTitle: 'Audio script',
      transcriptHint: 'Tap a sentence to replay that fragment',
      source: '🔊 In the recording',
      correctIs: (a) => 'Correct: ' + a,
      speaker: 'Speaker',
      pick: '—',
      checkAll: 'Check',
      nextText: 'Another variant',
      byKesTitle: 'By codifier',
      kes: { '1.2.1': 'Main idea', '1.2.2': 'Specific information', '1.2.3': 'Full understanding' },
      doneScore: (c, tot) => `✓ Done · ${c}/${tot} pts`,
      tasksPts: (n, pts) => `${n} task${n === 1 ? '' : 's'} · ${pts} point${pts === 1 ? '' : 's'}`,
      maxPts: (pts) => `${pts} point${pts === 1 ? '' : 's'} max for this part`,
      pointsWord: (pts) => (pts === 1 ? 'point' : 'points'),
      tfns: ['True', 'False', 'Not stated'],
      tfnsInstr: 'True / False / Not stated — mark each statement',
      cat: { match: 'Task 1 · Match the speakers', tf: 'Task 2 · True / False / Not stated', mc: 'Multiple choice' },
      catShort: { match: 'matching', tf: 'true/false', mc: 'multiple choice' },
      allVariants: 'Variants',
    },
    vocab: {
      sub: 'Theme of the week · 15 words a day',
      dailyTitle: 'Daily goal',
      dailyDone: (g) => `Daily goal done — ${g} words 🎉`,
      dailyLeft: (c, g) => `${c} of ${g} words today`,
      startDaily: 'Practise words',
      practiceMore: 'More cards',
      dueNote: (n, w) => `${n} ${w} to review`,
      dueNone: 'New words from this week\'s theme',
      learning: 'Theme of the week: ',
      learningSub: 'New words come from here; review is mixed',
      pickTheme: 'Choose the theme of the week',
      searchPlaceholder: 'Search a word or phrase…',
      searchEmpty: 'Nothing found',
      searchCount: (n) => `${n} found`,
      searchTitle: 'Dictionary', searchBtn: 'Dictionary',
      learnedOf: (a, b) => `learned ${a} of ${b}`,
      inProgress: (n) => `${n} in progress`,
      tapToFlip: 'Tap to see the translation',
      dontKnow: "Don't know",
      know: 'I know it',
      mNew: 'New word', mPreview: 'Get to know', mTrain: 'Practice',
      mChoose: 'Choose the translation', mCloze: 'Fill the gap', mType: 'Type in English',
      next: 'Next →', correct: '✓ Correct!', wrongIs: (a) => '✗ Answer: ' + a,
      typePlaceholder: 'type in English…', hintRu: (ru) => 'hint: ' + ru,
      finaleCardTitle: (th) => '"' + th + '" mastered! 🏆',
      finaleCardSub: 'Week finale: lock it in with writing',
      finaleTitle: 'Week finale',
      finaleSub: (th) => 'Theme "' + th + '" — use it in the written part',
      finaleWrite: (sec) => sec + ' on the theme',
      finalePickNew: '🔄 Choose a new theme',
      finaleNoTasks: 'No writing tasks for this theme yet',
      finaleCeleb: 'Theme mastered! 🏆',
      themeWeekLabel: (th) => 'Theme of the week: ' + th,
      finaleDoneBadge: '🏆 done',
      dayClosed: 'Daily vocabulary goal done! 🎉',
      keepGoing: 'Keep going!',
      toThemes: 'Themes',
    },
    // drill
    loadingTasks: 'Loading tasks…', allTopics: 'All topics',
    allTopicsSub: 'A random round of 15 tasks', byCodifier: 'Topics',
    mistakes: 'Practice your mistakes', mistakesSub: (n, w) => `${n} ${w} to review`,
    tasksWord: ['task', 'tasks', 'tasks'], varWord: ['variant', 'variants', 'variants'], roundsWord: ['round', 'rounds', 'rounds'], streakLabel: 'streak',
    topicsWord: ['topic', 'topics', 'topics'], whyCorrect: 'Correct!', whyCheck: 'Compare with the correct answer above.',
    enterAnswer: 'Type your answer', check: 'Check', next: 'Next', finish: 'Finish round',
    why: 'Why', correctIs: (k) => 'Correct answer: ' + k, baseWord: 'Word given',
    more15: 'One more round', otherTopic: 'Other topic', toHome: 'Home',
    rStreak: 'Streak', rXp: 'XP', rPack: 'Pack', rFreeze: 'Freeze', freezeSaved: 'saved your streak',
    dayWord: (s) => s === 1 ? 'day' : 'days',
    praiseHigh: 'great pace!', praiseMid: 'good job', praiseLow: 'keep practising',
    accLine: (acc, praise) => `${acc}% correct · ${praise}`,
    // writing (ЕГЭ — два задания, тексты общие)
    wLoading: 'Loading writing tasks…', wPickSub: 'Pick a task and write your answer', wAllLetters: 'Others',
    wLetterFrom: (n) => 'Email from ' + n, wFrom: (n) => 'From ' + n,
    wCheck: 'Check my writing', wRecheck: 'Check again',
    wFrame: 'Writing frame', wIdeas: 'Ideas: what to write about', wConnectors: 'Linkers',
    wVerdictDefault: 'Checked against the official criteria.',
    wErrorsTitle: 'Fixes: before → after', wCorrectedTitle: 'Corrected version',
    wMyWorks: 'My writing', wWorksSub: (n) => `${n} saved`,
    wWorksEmpty: 'Your checked writing will appear here — come back to re-read it before the exam.',
    wYourText: 'Your answer', wTaskPrompt: 'Task',
    wWords: (n, w) => `${n} ${w}`, wordsWord: ['word', 'words', 'words'],
    wErrShort: 'Write your answer first (at least a few sentences).',
    wErrServer: (s) => 'Check failed: ' + s,
    // progress
    progTitle: 'My progress', bySection: 'By section',
    solved: (a, c) => `done ${a} · correct ${c}`, noSolved: 'no tasks solved yet',
    progDone: (d, m) => `${d} of ${m} done`,
    avgTitle: 'Average writing score', avgSub: (n) => `essays checked: ${n}`, avgCrit: 'by the official criteria',
    achTitle: 'Achievements', changeName: 'Change name', reset: 'Reset',
    resetConfirm: 'Reset all progress on this device?',
    soundOn: '🔊 Sound: on', soundOff: '🔇 Sound: off',
    heroWord: ['hero', 'heroes', 'heroes'],
    // rewards / perks
    tokensLabel: (n, w) => `${w} earned`, tokenWord: ['token', 'tokens', 'tokens'],
    perksSub: 'Perks from your teacher. Get a badge and show it in class.',
    skinsTitle: 'XP bar skins', redeemedTitle: 'Used',
    skinEquipped: 'On', skinEquip: 'Equip',
    skinOn: '✅ Equipped now', skinOpen: '✅ Unlocked', perkEnough: '✅ Enough tokens', perkNeed: (n) => '🎟 ' + n + ' more needed',
    levelsTitle: 'Levels & ranks', levelsHow: 'XP builds up as you study: +10 for every correct answer, +30 for a perfect round (no mistakes). More XP — higher rank. Your level is highlighted.',
    ptsSpend: (n) => 'Spends: ' + n + ' 🎟', ptsRedeem: 'Redeem', perkChoose: 'Choose',
    // Онбординг: дата экзамена
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    examWhenTitle: (exam) => 'When is your ' + exam + '?',
    examWhenSub: 'I will put a countdown on the home screen. You can change the date later.',
    examMonthLabel: 'Month', examYearLabel: 'Year', examNext: 'Next →', examSkip: "Don't know yet",
    // Счётчик
    countdownTitle: 'Until the exam',
    countdownFuture: (w, exam) => '≈ ' + w + (w === 1 ? ' week' : ' weeks') + ' until ' + exam,
    countdownDays: (d, exam) => d + (d === 1 ? ' day' : ' days') + ' until ' + exam,
    countdownThisMonth: (exam) => exam + ' is this month 💪',
    countdownSetTitle: 'When is the exam?',
    countdownSetPrompt: 'Set the date — I will start a countdown',
    // Weekly study plan
    planCardTitle: 'Weekly plan',
    planToCover: (n) => '~' + n + (n === 1 ? ' task' : ' tasks') + ' a week',
    planPerDay: (m) => '≈ ' + m + ' a day',
    planMiniSec: (name, n) => name + ' ' + n,
    planCardSub: 'to master everything by the exam',
    planMinCardSub: "can't cover it all — keeping a minimum",
    planMinShort: (n) => 'minimum ~' + n + '/wk: all topics + words',
    planDoneCard: 'All done! 🎉 Keep reviewing.',
    planTitle: 'Study plan',
    planWeeksLeft: (w) => w + (w === 1 ? ' week' : ' weeks') + ' until the exam',
    planSummary: (n, m) => '~' + n + ' tasks a week · ≈ ' + m + ' a day',
    planMinBanner: 'Not enough time to master everything. First do EVERY topic at least 5 tasks and keep 15 words a day — that covers all topics. Time left — push topics to a crown.',
    planSecLine: (done, tot) => 'mastered ' + done + ' of ' + tot + ' topics',
    planSecRem: (r, w) => '~' + r + ' · ' + w + '/wk',
    planSecDone: '✅ all mastered',
    planTopicsHdr: 'What is left by topic',
    planTopicLeft: (k) => k + ' left',
    planVocabTitle: 'Vocabulary',
    planVocabLine: (l, tot) => '15 words/day · mastered ' + l + ' of ' + tot,
    planAllDone: 'Whole bank done — great job! Keep reviewing weak topics.',
    readFmt: { '1.3.1': 'Headings', '1.3.2': 'Gapped text', '1.3.3': 'Multiple choice' },
    planGoals: {
      full: { name: 'Whole bank', desc: 'solve every question' },
      master: { name: 'Master all topics', desc: 'every topic to a crown' },
      light: { name: 'All topics once', desc: 'a quick pass over topics' },
    },
    planMark: { ok: '✅', tight: '⚠️', hard: '🔒', done: '🎉' },
    planMarkText: { ok: 'doable', tight: 'intense', hard: "won't fit", done: 'done' },
    planChooseHdr: 'Your goal',
    planRecommended: 'recommended',
    planGoalCardSub: (name, day) => name + ' · ' + day,
    planHardHint: "Not reachable at the usual pace in the time left — pick an easier goal or push harder.",
    // Советы (для ЕГЭ контента пока нет, memosFile=null → не используется)
    tipsTitle: (sec) => sec + ' · Speaky tips',
    tipFormat: '📋 Format', tipTime: '⏱ Time', tipHow: '✅ How to do it', tipMistakes: '⚠️ Common mistakes',
    examIntro: [
      { img: './assets/spiky-talk.png', title: 'What is the EGE', text: 'The English EGE has two parts.\nWritten (~3h10m): listening, reading, grammar & vocabulary, writing.\nSpeaking (~17 min) — a separate part.\nMax 100 points: 22 to pass, 40+ for university.' },
      { img: './assets/spiky-check.png', title: 'Written part', text: 'Four sections, you manage the time yourself:\n1) Listening (~30 min).\n2) Reading (~30 min).\n3) Grammar & vocabulary (~15 min).\n4) Writing — 2 tasks (~50 min).' },
      { img: './assets/spiky-idea.png', title: 'Writing — two tasks', text: 'Task 37 — an email to a pen-friend: answer all questions AND ask 3 of your own (~100 words).\nTask 38 — an opinion text based on a chart, with 6 aspects (~200–250 words).\nMiss an aspect or a question and you lose points.' },
      { img: './assets/spiky-thumb.png', title: "It's all about practice", text: "Here you'll train every section: grammar, vocabulary, reading, email and essay.\nIn each section Speaky shows how to do the task and the time to spend.\nLet's go! 💪" },
    ],
    rewSub: 'XP bar skins. Unlocked by levels and heroes you collect.',
    badgeShow: '👀 Show this screen to your teacher', badgeDone: 'Done',
    // celebration moments
    celHeroT: 'HERO!', celLevelT: (lvl, t) => 'Level ' + lvl + ' · ' + t,
    celStreakT: (n) => n + ' days in a row!', celFreezeT: 'Freeze earned',
    celTokenT: (n, w) => '+' + n + ' ' + w, celTokenText: (name) => `A token for you, ${name}. Trade it for a perk with your teacher 🎟`,
    celAchText: (desc, phrase) => 'Achievement: ' + desc + '. ' + phrase,
    celNext: 'Next →', celClaim: 'Claim!',
    achGot: '✅ Earned', achLocked: '🔒 Not yet', modalClose: 'Got it',
    friend: 'friend',
    egeSpeaking: {
      loading: 'Loading tasks…',
      pick: 'Choose a task type',
      taskCount: (n) => `${n} ${n === 1 ? 'task' : 'tasks'}`,
      doneOf: (d, n) => `${d}/${n} done`,
      randomTask: 'Random task',
      catRead: 'Task 1 · Read aloud',
      catAsk: 'Task 2 · Ask questions',
      catInterview: 'Task 3 · Interview',
      catCompare: 'Task 4 · Compare photos',
      playInterview: 'Play the interview and answer in the pauses',
      yourTurn: '🎤 Now record your answer:',
      recStart: '🎤 Record', recStop: '⏹ Stop', recAgain: '↺ Re-record',
      recOn: 'Recording… speak', micErr: 'No microphone access — allow it in the browser',
      aiCheck: 'Check with AI',
      aiNoRec: 'Record your answer first',
      aiRecognizing: 'Recognising speech…',
      aiEvaluating: 'Assessing…',
      aiErr: 'Failed:',
      aiEmpty: 'No speech recognised — record again, closer to the mic.',
      aiTranscript: 'What the AI heard',
      aiNote: 'The AI judges the recognised text (content, grammar, completeness) by the official FIPI limits (1/4/5/10). Pronunciation is best checked with a teacher.',
      listenModel: 'Listen to the model',
      frameRead: 'Reading tips', frameAsk: 'Question frame', frameInterview: 'Useful phrases', frameCompare: 'Speaking frame',
      phraseBank: 'Phrase bank',
      sampleQuestions: 'Model questions',
      sampleTitle: 'Model answers',
      sampleTemplate: 'Model answer (template)',
      compareTemplate: "I'd like to compare these two photos. In the first picture I can see … , while in the second one there is … . Although both photos share the same theme, they are quite different. The main difference is that … , whereas … . Speaking about the advantages and disadvantages, the first option is … , but … ; the second one is … , though … . Personally, I would prefer … because … . That's why I think these photos illustrate our project well.",
      doneBtn: 'Done, practised',
      donePraise: (name) => `${name}, great speaking practice! 🎤`,
      doneSub: 'Self-check against the criteria, and try the AI feedback.',
      more: 'Another task',
    },
    mock: {
      loading: 'Preparing variants…',
      title: 'Mock exam',
      pickVariant: 'Choose a variant',
      variant: (n) => 'Variant ' + n,
      ptsShort: 'pts',
      notTaken: 'not taken yet',
      lastResult: (s, m) => `last time: ${s} of ${m}`,
      pointA: 'Point A',
      pointASub: 'Take your first mock to fix your starting point — then watch your progress.',
      heroTitle: 'Mock exam',
      heroSub: 'A full FIPI-style paper with a timer. No hints — the real thing.',
      rules: [
        'A hard timer runs for the whole paper — at zero everything is submitted automatically.',
        'No hints, no checking, no script — your score comes at the end.',
        'Your writing is graded by AI (needs internet), the rest by answer keys.',
      ],
      startTitle: (n) => `Variant ${n} — start?`,
      startWarn: (min) => `A ${min}-minute timer starts at once and won't stop. Find a quiet place.`,
      startBtn: 'Start',
      sectionOf: (a, b) => `Section ${a} of ${b}`,
      nextSection: 'Next section →',
      finishBtn: 'Finish and see the score',
      finishTitle: 'Finish the exam?',
      finishWarn: 'Answers are taken as they are — no changes after this.',
      keepGoing: 'Keep working',
      listenHint: 'Play the recording. In the real exam it plays twice — listen carefully.',
      answerPh: 'Answer',
      rubricsLabel: 'Statements:',
      matchTitle: 'Match the texts to the questions:',
      gapsTitle: 'Fill the gaps with the sentence parts:',
      partsLabel: 'Parts:',
      tfTitle: 'Mark each statement:',
      tfLabels: ['True', 'False', 'Not stated'],
      writePh: 'Write your answer here…',
      writeInstr: 'Write your answer, keep the format.',
      writeWords: (a, b) => `Length: ${a}–${b} words. Keep the format.`,
      words: (n) => `${n} ${n === 1 ? 'word' : 'words'}`,
      scoring: 'Scoring…',
      timeUp: '⏱ Time is up — we kept what you did',
      pointsScored: (p) => `that's ${p}% of the written part`,
      writtenPartNote: 'This is the written part (max 62). Speaking adds up to 20 more.',
      pointsFull: (p) => `that's ${p}% of the full score`,
      fullPartNote: 'Full exam: written + speaking.',
      testProj: (n) => `≈ ${n} / 100 test points`,
      testProjNote: 'Projection: same level on the speaking part. Primary → test by the FIPI table.',
      gradeProj: (g) => `Projected mark: ${g}`,
      gradeProjNote: 'Projected 5-point mark (speaking assumed at the same level).',
      bySection: 'By section',
      byKes: 'By codifier (KES)',
      writingResult: 'Writing — AI grade',
      backToList: 'Back to variants',
      writePending: 'Writing could not be graded (no internet) — it is not in the score.',
      writeEmpty: 'Writing left empty — 0 for the section.',
    },
    mockPrompt: {
      firstTitle: 'Set your Point A',
      firstText: 'Take your first mock exam — we\'ll fix your starting point and track your progress from there.',
      dueTitle: 'Time for a mock',
      dueText: 'A month has passed since your last mock. Check your form on a full timed paper.',
      weeklyText: 'Less than a month to the exam — mocks are weekly now. Time for a new one!',
      go: 'Take the mock',
      later: 'Later',
    },
    sections: { vocab: 'Topic Vocabulary', grammar: 'Grammar', wordform: 'Word formation', reading: 'Reading', listening: 'Listening', writing: 'Writing', speaking: 'Speaking', mock: 'Mock exam', lexis: 'Vocabulary', email: 'Email', essay: 'Essay' },
    sectionMeta: { vocab: 'theme of the week · 15 words a day', grammar: '389 tasks · grammar', wordform: '728 tasks · word forms', reading: '469 tasks · 3 formats', listening: 'FIPI audio · multiple choice', writing: 'writing', speaking: '184 tasks · recorder + AI', mock: 'full timed paper', lexis: '728 tasks · vocabulary', email: 'task 37 · K1–K3', essay: 'task 38 · K1–K5' },
    ranks: ['Rookie', 'Trainee', 'Skilled', 'Pro', 'Master', 'Legend'],
    skins: {
      aurora: { name: 'Aurora', desc: 'Purple → honey', need: 'available now', how: 'A skin is the colour of your XP bar at the top. "Aurora" (purple → honey) is available right away — equip it in one tap.' },
      sunset: { name: 'Sunset', desc: 'Berry → orange', need: 'Level 2', how: 'A skin colours your XP bar. "Sunset" (berry → orange) unlocks at level 2 — earn XP for correct answers.' },
      grape: { name: 'Grape', desc: 'Deep purple', need: 'Level 4', how: 'A skin colours your XP bar. "Grape" (deep purple) unlocks at level 4.' },
      honeycomb: { name: 'Honey', desc: 'Warm honey', need: '2 heroes', how: 'A skin colours your XP bar. "Honey" unlocks once you become a Hero twice (collect the pack twice).' },
      guru: { name: 'Guru', desc: 'Full S&S spectrum', need: 'Reach "Legend"', how: 'A skin colours your XP bar. "Guru" (the full Speak & Smile spectrum) unlocks at the top rank "Legend" — level 6.' },
    },
    ach: {
      first: { title: 'First step', desc: 'First round', how: 'Finish your very first round and earn your first XP. Every journey starts here!' },
      perfect: { title: 'Perfect', desc: 'A perfect round', how: 'Finish a whole round without a single mistake. A perfect round also earns you a streak freeze.', rep: (n) => 'Perfect rounds: ' + n + ' · +' + n + ' 🧊' },
      hero: { title: 'Hero', desc: 'Collect the pack', how: 'Complete the whole weekly pack — clear every section for the period. A pack earns a 🎟 token for a teacher perk.', rep: (n) => 'Packs collected: ' + n + ' · +' + n + ' 🎟' },
      hundred: { title: 'Century', desc: '100 tasks solved', how: 'Solve 100 tasks in total, across any sections. The counter adds up by itself.' },
      week: { title: 'On a roll', desc: '7-day streak', how: 'Study 7 days in a row — push your streak 🔥 to seven. Hit your daily vocab goal each day to keep it growing. Reach 7/14/30/50/100 for +2 🎟; break it and climb back and you earn them again.', rep: (n) => 'Your best streak: ' + n + ' days' },
      gold: { title: 'Topic master', desc: 'A gold crown', how: 'Take any topic all the way to a gold crown 👑 — lots of solved tasks at high accuracy.', rep: (n) => 'Gold crowns: ' + n },
      fivehundred: { title: 'Five hundred', desc: '500 tasks solved', how: 'Solve 500 tasks in total. That is real volume — serious progress.' },
      frosty: { title: 'Stocked up', desc: '3 freezes saved', how: 'Save up 3 streak freezes 🧊 (one for each perfect round). A freeze covers a missed day.' },
    },
    perks: {
      hint: { title: 'Hint on a test', desc: 'One hint during a test', how: 'A real perk from your teacher: one hint during a test. Costs 2 🎟. Redeem it for a code and show it to your teacher. Tokens come from completed packs (Hero) and streak milestones.' },
      nohw: { title: 'No-homework pass', desc: 'Come to class with no homework', how: 'A real perk: come to class with no homework. Costs 4 🎟. Redeem for a code to show your teacher. Earn tokens from packs and streaks.' },
      points: { title: 'Test bonus points', titleN: (n) => '+' + n + (n === 1 ? ' point' : ' points') + ' on a test', desc: 'Trade tokens for points: 1 🎟 = +1 point', how: 'A real bonus from your teacher: add points to your test result. 1 token = +1 point, from 1 to 10 per test (as many tokens as you have). Choose how many to spend — get a "+N points" code to show your teacher.', chooseHelp: (bal) => '1 token = +1 test point. You have ' + bal + ' 🎟. Choose how many to add (up to 10).', chooseBig: (n) => '+' + n, badgeShow: '👀 Show the code to your teacher — they add the test points' },
      coins: { title: '"Your School" coins', titleN: (n) => (n * 5) + ' "Your School" coins', desc: 'Trade tokens for coins: 1 🎟 = 5 coins', how: 'A real exchange: turn tokens into coins in the "Your School" app — spend them on real purchases in the school store. 1 token = 5 coins. Choose how many tokens to exchange — get a code, show it to your teacher to credit the coins.', chooseHelp: (bal) => '1 token = 5 "Your School" coins. You have ' + bal + ' 🎟. Choose how many to exchange.', chooseBig: (n) => (n * 5) + ' coins', badgeShow: '👀 Show the code to your teacher — they credit "Your School" coins' },
    },
    voice: {
      homeIdle: ['{name}, your streak is waiting. Keep it up 😎', '{name}, your move. One round — go.', '{name}, one round and you are in.', 'So, {name}, shall we?'],
      homeDone: ["Goal done, {name}. But who said stop? 😏", '{name}, day done. One more?', '{name}, target hit. More? 😏'],
      high: ['{score}, {name}. Clean 😎', '{name}, nice. All 15 next time? 😉', 'Strong, {name}. Keep going.', '{score} — {name} is on fire 🔥'],
      mid: ['{score}, {name}. Good, but you can do cleaner.', 'Keep going, {name}. Nail the next one.', '{name}, solid. Almost perfect.'],
      low: ['{name}, that is not your limit. Rematch?', 'It happens, {name}. The review helped — go again.', "{name}, doesn't count. One more round and show your best."],
      hero: ['{name} — HERO. The whole pack is yours 🦸', 'Full pack, {name}. Respect 🤝', '{name}, full pack collected. Nice 🦸'],
      celHero: ['The whole pack in one go, {name}. That is a level 🦸', '{name}, you took the whole pack. Fire!', 'Grammar, vocabulary, writing — all yours, {name}.'],
      celLevel: ['You are growing fast, {name}. Onwards and upwards!', 'New level reached, {name}. That is the way 💪', '{name}, level up. The exam is closer.'],
      celStreak: ['A winning habit, {name}. Hold on 🔥', '{name}, so many days in a row — character!', 'Every day in action, {name}. That is the result.'],
      celFreeze: ['A freeze in your pocket, {name}. One missed day is fine now 🧊', '{name}, your streak is protected. Relax.'],
      celAch: ['New achievement, {name}! Your collection grows 🏅', '{name}, a new badge. Keep it up!', 'One more badge is yours, {name}. Nice.'],
    },
  },
};
