// strings.js — все тексты интерфейса на двух языках.
// ОГЭ = ru (родной интерфейс), ЕГЭ = en (полное погружение, уровень B1).
// Активный набор выбирается в exam.js по exam.lang.

// Склонение русского числительного: forms = [1, 2-4, 5-0]. Локально, чтобы strings.js
// не зависел от exam.js (там есть plural, но импорт сюда дал бы цикл).
function pluralRu(n, forms) {
  const m10 = n % 10, m100 = n % 100;
  if (m10 === 1 && m100 !== 11) return forms[0];
  if (m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14)) return forms[1];
  return forms[2];
}

export const STRINGS = {
  ru: {
    // splash
    brandline: 'Speak & Smile · Тренажёр ОГЭ',
    greetHi: 'Привет! Я Спики 👋', greetQ: 'Как тебя зовут?',
    namePlaceholder: 'Твоё имя', go: 'Поехали!',
    offlineNote: 'Всё работает оффлайн. Прогресс хранится на твоём устройстве — без аккаунтов.',
    // nav
    navHome: 'Главная', navProgress: 'Прогресс', navRewards: 'Награды',
    // home
    welcomeBack: 'С возвращением', today: 'Сегодня', week: 'За неделю', lvl: 'Ур.',
    toRank: (r, n) => `до «${r}»: ${n} XP`, maxRank: 'максимальное звание',
    empty: 'пока пусто',
    goalTitle: 'Цель дня', goalDone: (s) => `Готово на сегодня — ${s}`, goalIdle: 'Сделай хотя бы 1 раунд',
    packTitle: '🦸 Пак недели', packOf: (n, tot) => `${n} из ${tot}`,
    packNote: 'Пройди раунд в каждом разделе — собери все и стань Героем',
    sectionsTitle: 'Разделы', myProgress: 'Мой прогресс', rewards: 'Награды',
    soonTitle: 'Аудирование', soonMeta: 'появится в следующем обновлении', soon: 'Скоро',
    soonScreenTitle: 'Скоро', soonScreenText: 'Этот раздел в разработке — добавим в одном из следующих обновлений.',
    // reading (чтение)
    reading: {
      pick: 'Выбери тип задания',
      tfTitle: 'Верно · Неверно · Не сказано', tfSub: '28 текстов · по 7 утверждений',
      matchTitle: 'Текст ↔ вопрос', matchSub: '38 заданий · тексты A–F',
      readFirst: 'Прочитай текст и оцени каждое утверждение',
      matchInstr: 'Подбери к каждому тексту A–F нужный вопрос',
      questionsTitle: 'Вопросы',
      tf: ['Верно', 'Неверно', 'Не сказано'],
      pickQ: '—',
      correctNum: (n) => 'Верно: ' + n,
      nextText: 'Другой текст',
      why: 'Почему', evidenceLabel: 'В тексте',
      notStatedNote: 'В тексте об этом не говорится.',
    },
    readingEge: {
      pick: 'Выбери тип задания',
      headingsTitle: 'Подбор заголовков', headingsSub: '56 заданий · 7 текстов ↔ 8 заголовков',
      gapsTitle: 'Вставка частей', gapsSub: '57 заданий · вставь пропущенные части',
      mcTitle: 'Выбор ответа', mcSub: '51 текст · по несколько вопросов',
      headingsInstr: 'Подбери к каждому тексту (A–G) заголовок. Один лишний.',
      gapsInstr: 'Заполни каждый пропуск (A–F) нужной частью. Одна лишняя.',
      mcInstr: 'Прочитай текст и выбери правильный ответ на каждый вопрос.',
      headingsLabel: 'Заголовки', partsLabel: 'Части', questionsTitle: 'Вопросы',
      readFirst: 'Читай внимательно',
      pickN: '—',
      correctNum: (n) => 'Верно: ' + n,
      nextText: 'Другое задание',
      why: 'Почему',
    },
    // vocab (лексика — тема недели + флэшкарты/SRS)
    vocab: {
      sub: 'Тема недели · 15 слов в день',
      dailyTitle: 'Норма дня',
      dailyDone: (g) => `Норма выполнена — ${g} слов 🎉`,
      dailyLeft: (c, g) => `${c} из ${g} слов сегодня`,
      startDaily: 'Тренировать слова',
      practiceMore: 'Ещё карточки',
      dueNote: (n, w) => `${n} ${w} к повторению`,
      dueNone: 'Новые слова из темы недели',
      learning: 'Тема недели: ',
      learningSub: 'Новые слова берём отсюда; повторение — вперемешку',
      pickTheme: 'Выбрать тему недели',
      searchPlaceholder: 'Найти слово или фразу…',
      searchEmpty: 'Ничего не найдено',
      searchCount: (n) => `найдено: ${n}`,
      searchTitle: 'Словарь', searchBtn: 'Словарь',
      learnedOf: (a, b) => `освоено ${a} из ${b}`,
      inProgress: (n) => `в работе ${n}`,
      tapToFlip: 'Нажми, чтобы увидеть перевод',
      dontKnow: 'Не помню',
      know: 'Помню',
      dayClosed: 'Норма дня по лексике закрыта! 🎉',
      keepGoing: 'Так держать!',
      toThemes: 'К темам',
    },
    // drill
    loadingTasks: 'Загружаю задания…', allTopics: 'Все темы',
    allTopicsSub: 'Случайный раунд из 15 заданий', byCodifier: 'Темы по кодификатору',
    mistakes: 'Работа над ошибками', mistakesSub: (n, w) => `${n} ${w} на повторение`,
    tasksWord: ['задание', 'задания', 'заданий'], roundsWord: ['раунд', 'раунда', 'раундов'], streakLabel: 'серия',
    topicsWord: ['тема', 'темы', 'тем'], whyCorrect: 'Верно!', whyCheck: 'Сверь с правильным вариантом выше.',
    enterAnswer: 'Введи ответ', check: 'Проверить', next: 'Дальше', finish: 'Завершить раунд',
    why: 'Почему', correctIs: (k) => 'Правильно: ' + k, baseWord: 'Опорное слово',
    more15: 'Ещё 15', otherTopic: 'Другая тема', toHome: 'На главную',
    rStreak: 'Серия', rXp: 'Опыт', rPack: 'Пак', rFreeze: 'Заморозка', freezeSaved: 'спасла серию',
    dayWord: (s) => s === 1 ? 'день' : 'дн.',
    praiseHigh: 'отличный темп!', praiseMid: 'хороший результат', praiseLow: 'есть над чем поработать',
    accLine: (acc, praise) => `${acc}% верных ответов · ${praise}`,
    // writing (ОГЭ — одно письмо)
    wLoading: 'Загружаю темы писем…', wPickSub: 'Выбери письмо друга — ответь 100–120 слов',
    wLetterFrom: (n) => 'Письмо от друга — ' + n, wFrom: (n) => 'Письмо от ' + n,
    wCheck: 'Проверить письмо', wRecheck: 'Проверить заново',
    wVerdictDefault: 'Проверено по критериям К1–К4.',
    wErrorsTitle: 'Ошибки: было → стало', wCorrectedTitle: 'Исправленный вариант',
    wMyWorks: 'Мои работы', wWorksSub: (n) => `сохранено: ${n}`,
    wWorksEmpty: 'Здесь будут твои проверенные работы — пиши и возвращайся перечитать перед экзаменом.',
    wYourText: 'Твой ответ', wTaskPrompt: 'Задание',
    wWords: (n, w) => `${n} ${w} · 100–120`, wordsWord: ['слово', 'слова', 'слов'],
    wErrShort: 'Напиши письмо (хотя бы несколько предложений).',
    wErrServer: (s) => 'Ошибка проверки: ' + s,
    // progress
    progTitle: 'Мой прогресс', bySection: 'По разделам',
    solved: (a, c) => `решено ${a} · верно ${c}`, noSolved: 'пока нет решённых заданий',
    avgTitle: 'Средний балл за письма', avgSub: (n) => `проверено писем: ${n}`, avgCrit: 'по критериям К1–К4',
    achTitle: 'Достижения', changeName: 'Изменить имя', reset: 'Сбросить',
    resetConfirm: 'Сбросить весь прогресс на этом устройстве?',
    soundOn: '🔊 Звук: вкл', soundOff: '🔇 Звук: выкл',
    heroWord: ['герой', 'героя', 'героев'],
    // rewards / perks
    tokensLabel: (n, w) => `${w} за работу`, tokenWord: ['жетон', 'жетона', 'жетонов'],
    perksSub: 'Привилегии у учителя. Получи бейдж и покажи его на уроке.',
    skinsTitle: 'Образы XP-полосы', redeemedTitle: 'Использованные',
    skinEquipped: 'Надето', skinEquip: 'Надеть',
    skinOn: '✅ Надет сейчас', skinOpen: '✅ Открыт', perkEnough: '✅ Жетонов хватает', perkNeed: (n) => '🎟 Нужно ещё ' + n,
    levelsTitle: 'Уровни и звания', levelsHow: 'XP копится за занятия: +10 за каждый верный ответ, +30 за идеальный раунд (без ошибок). Больше XP — выше звание. Твой уровень подсвечен.',
    ptsSpend: (n) => 'Спишется: ' + n + ' 🎟', ptsRedeem: 'Обменять', perkChoose: 'Выбрать',
    // Онбординг: дата экзамена
    months: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
    examWhenTitle: (exam) => 'Когда сдаёшь ' + exam + '?',
    examWhenSub: 'Поставлю счётчик на главной. Дату можно изменить позже.',
    examMonthLabel: 'Месяц', examYearLabel: 'Год', examNext: 'Дальше →', examSkip: 'Пока не знаю',
    // Счётчик на главной
    countdownTitle: 'До экзамена',
    countdownFuture: (w, exam) => '≈ ' + w + ' ' + pluralRu(w, ['неделя', 'недели', 'недель']) + ' до ' + exam,
    countdownDays: (d, exam) => d + ' ' + pluralRu(d, ['день', 'дня', 'дней']) + ' до ' + exam,
    countdownThisMonth: (exam) => exam + ' уже в этом месяце 💪',
    countdownSetTitle: 'Когда экзамен?',
    countdownSetPrompt: 'Поставь дату — включу счётчик',
    // Недельный план подготовки
    planCardTitle: 'План недели',
    planToCover: (n) => '~' + n + ' ' + pluralRu(n, ['задание', 'задания', 'заданий']) + ' в неделю',
    planPerDay: (m) => '≈ ' + m + ' в день',
    planMiniSec: (name, n) => name + ' ' + n,
    planCardSub: 'чтобы освоить всё к экзамену',
    planMinCardSub: 'весь объём не успеть — держим минимум',
    planMinShort: (n) => 'минимум ~' + n + '/нед: все темы + слова',
    planDoneCard: 'Весь объём пройден! 🎉 Повторяй и закрепляй.',
    planTitle: 'План подготовки',
    planWeeksLeft: (w) => 'До экзамена ' + w + ' ' + pluralRu(w, ['неделя', 'недели', 'недель']),
    planSummary: (n, m) => '~' + n + ' заданий в неделю · ≈ ' + m + ' в день',
    planMinBanner: 'Времени мало, чтобы освоить всё. Сначала пройди КАЖДУЮ тему хотя бы по 5 заданий и держи 15 слов в день — так закроешь все темы. Останется время — добивай до короны.',
    planSecLine: (done, tot) => 'освоено ' + done + ' из ' + tot + ' тем',
    planSecRem: (r, w) => '~' + r + ' · ' + w + '/нед',
    planSecDone: '✅ всё освоено',
    planTopicsHdr: 'Что осталось по темам',
    planTopicLeft: (k) => 'осталось ' + k,
    planVocabTitle: 'Лексика',
    planVocabLine: (l, tot) => '15 слов/день · освоено ' + l + ' из ' + tot,
    planAllDone: 'Весь банк пройден — отличная работа! Повторяй и закрепляй слабые темы.',
    readFmt: { '1.3.1': 'Подбор заголовков', '1.3.2': 'Вставка частей', '1.3.3': 'Множественный выбор' },
    planGoals: {
      full: { name: 'Весь банк', desc: 'прорешать все вопросы' },
      master: { name: 'Освоить все темы', desc: 'каждую тему до короны' },
      light: { name: 'Все темы по разу', desc: 'быстрый проход по всем темам' },
    },
    planMark: { ok: '✅', tight: '⚠️', hard: '🔒', done: '🎉' },
    planMarkText: { ok: 'реально', tight: 'интенсивно', hard: 'не успеть', done: 'пройдено' },
    planChooseHdr: 'Твоя цель',
    planRecommended: 'рекомендуем',
    planGoalCardSub: (name, day) => name + ' · ' + day,
    planHardHint: 'За оставшееся время эту цель не взять при обычном темпе — выбери полегче или поднажми.',
    // Советы Спики по разделу
    tipsTitle: (sec) => sec + ' · советы Спики',
    tipFormat: '📋 Формат', tipTime: '⏱ Время', tipHow: '✅ Как делать', tipMistakes: '⚠️ Частые ошибки',
    // Рассказ о формате (карточки-слайды). Числа: всего 68, порог 29, письмо 10 (проверено); время — из памяток.
    examIntro: [
      { img: './assets/spiky-talk.png', title: 'Что такое ОГЭ', text: 'Экзамен по английскому — это две части.\nПисьменная (≈2 часа): аудирование, чтение, грамматика и лексика, письмо.\nУстная — говорение (≈15 минут).\nВсего 68 баллов: на тройку хватит 29, на пятёрку — от 58.' },
      { img: './assets/spiky-check.png', title: 'Письменная часть', text: '4 раздела, время между ними распределяешь сам:\n1) Аудирование (≈30 мин) — слушаешь и отвечаешь.\n2) Чтение (≈25–30 мин).\n3) Грамматика и лексика (≈15–20 мин).\n4) Письмо (≈20–25 мин).' },
      { img: './assets/spiky-idea.png', title: 'Письмо и говорение', text: 'Письмо (задание 35) — личное письмо другу: 100–120 слов, 10 баллов.\nВажно: меньше 90 слов — ноль за всё задание!\nГоворение — отдельная часть: читаешь текст вслух и отвечаешь на вопросы.' },
      { img: './assets/spiky-thumb.png', title: 'Главное — тренировка', text: 'Здесь ты прокачаешь каждый раздел: грамматику, словообразование, чтение, письмо и лексику.\nВ каждом разделе Спики подскажет, как делать задание и сколько тратить времени.\nПоехали! 💪' },
    ],
    rewSub: 'Скины XP-полосы. Открываются за уровни и собранных героев.',
    badgeShow: '👀 Покажи этот экран учителю', badgeDone: 'Готово',
    // celebration moments
    celHeroT: 'ГЕРОЙ!', celLevelT: (lvl, t) => 'Уровень ' + lvl + ' · ' + t,
    celStreakT: (n) => n + ' дней подряд!', celFreezeT: 'Заморозка получена',
    celTokenT: (n, w) => '+' + n + ' ' + w, celTokenText: (name) => `Жетон в копилку, ${name}. Обменяй на привилегию у учителя 🎟`,
    celAchText: (desc, phrase) => 'Достижение «' + desc + '». ' + phrase,
    celNext: 'Дальше →', celClaim: 'Забрать!',
    achGot: '✅ Получено', achLocked: '🔒 Ещё не получено', modalClose: 'Понятно',
    friend: 'друг',
    // названия и подписи разделов (по id)
    sections: { vocab: 'Тематический словарь', grammar: 'Грамматика', wordform: 'Словообразование', reading: 'Чтение', writing: 'Письмо', speaking: 'Говорение', lexis: 'Лексика', email: 'Письмо (e-mail)', essay: 'Эссе' },
    sectionMeta: { vocab: 'тема недели · 15 слов в день', grammar: '661 задание · 15 тем', wordform: '437 заданий · 7 тем', reading: '28 текстов + 38 заданий', writing: 'задание 35 · К1–К4', speaking: 'скоро', lexis: '728 заданий', email: 'задание 37 · К1–К3', essay: 'задание 38 · К1–К5' },
    // звания / скины / ачивки / привилегии
    ranks: ['Новичок', 'Стажёр', 'Знаток', 'Профи', 'Мастер', 'Легенда'],
    skins: {
      aurora: { name: 'Аврора', desc: 'Фиолетовый → медовый', need: 'доступно сразу', how: 'Скин — это цвет твоей XP-полосы вверху экрана. «Аврора» (фиолетовый → медовый) доступна сразу, надевается одним тапом.' },
      sunset: { name: 'Закат', desc: 'Малина → оранжевый', need: 'Уровень 2', how: 'Скин раскрашивает XP-полосу. «Закат» (малина → оранжевый) открывается на 2-м уровне — копи XP за верные ответы.' },
      grape: { name: 'Виноград', desc: 'Глубокий фиолет', need: 'Уровень 4', how: 'Скин раскрашивает XP-полосу. «Виноград» (глубокий фиолет) открывается на 4-м уровне.' },
      honeycomb: { name: 'Медовый', desc: 'Тёплый медовый', need: '2 героя', how: 'Скин раскрашивает XP-полосу. «Медовый» открывается, когда станешь Героем 2 раза (соберёшь пак дважды).' },
      guru: { name: 'Гуру', desc: 'Весь спектр S&S', need: 'Звание «Легенда»', how: 'Скин раскрашивает XP-полосу. «Гуру» (весь спектр Speak & Smile) открывается с высшим званием «Легенда» — это 6-й уровень.' },
    },
    ach: {
      first: { title: 'Первый шаг', desc: 'Первый раунд', how: 'Реши свой самый первый раунд — заработай первые XP. Лиха беда начало!' },
      perfect: { title: 'Идеал', desc: 'Идеальный раунд', how: 'Пройди целый раунд без единой ошибки. За идеальный раунд ещё и заморозка серии в подарок.', rep: (n) => 'Идеальных раундов: ' + n + ' · +' + n + ' 🧊' },
      hero: { title: 'Герой', desc: 'Собери пак', how: 'Собери весь «пак недели» — закрой все разделы за период. За пак дают жетон 🎟 на привилегию у учителя.', rep: (n) => 'Собрано паков: ' + n + ' · +' + n + ' 🎟' },
      hundred: { title: 'Сотка', desc: '100 заданий решено', how: 'Реши 100 заданий всего (по любым разделам). Счётчик копится сам.' },
      week: { title: 'Неделя в деле', desc: 'Серия 7 дней', how: 'Занимайся 7 дней подряд — доведи серию 🔥 до семёрки. Каждый день закрывай норму лексики, чтобы серия росла. Дойдёшь до 7/14/30/50/100 — +2 🎟; порвётся и снова доберёшься — жетоны дадут опять.', rep: (n) => 'Твой рекорд серии: ' + n + ' дн.' },
      gold: { title: 'Мастер темы', desc: 'Золотая корона', how: 'Доведи любую тему до золотой короны 👑 — много решённых заданий с высокой точностью.', rep: (n) => 'Золотых корон: ' + n },
      fivehundred: { title: 'Полтысячи', desc: '500 заданий решено', how: 'Реши 500 заданий всего. Это уже серьёзный объём — настоящая прокачка.' },
      frosty: { title: 'Запасливый', desc: '3 заморозки в запасе', how: 'Накопи 3 заморозки серии 🧊 (по одной за каждый идеальный раунд). Заморозка прикрывает пропущенный день.' },
    },
    perks: {
      hint: { title: 'Подсказка на тесте', desc: 'Право на одну подсказку во время теста', how: 'Настоящая привилегия у преподавателя: одна подсказка во время теста. Стоит 2 🎟. Обменяешь — получишь код, покажи его учителю. Жетоны капают за собранные паки (Герой) и вехи серии.' },
      nohw: { title: 'Урок без ДЗ', desc: 'Прийти на урок без домашнего задания', how: 'Настоящая привилегия: прийти на урок без домашки. Стоит 4 🎟. Обменяешь — получишь код для учителя. Жетоны зарабатываешь за паки и серию.' },
      points: { title: 'Баллы к тесту', titleN: (n) => '+' + n + ' ' + pluralRu(n, ['балл', 'балла', 'баллов']) + ' к тесту', desc: 'Обменяй жетоны на баллы: 1 🎟 = +1 балл', how: 'Настоящий бонус у преподавателя: добавь баллы к результату теста. 1 жетон = +1 балл, можно от 1 до 10 за тест (сколько хватит жетонов). Выбираешь, сколько потратить, — получишь код «+N баллов», покажи учителю.', chooseHelp: (bal) => '1 жетон = +1 балл к тесту. У тебя ' + bal + ' 🎟. Выбери, сколько добавить (до 10).', chooseBig: (n) => '+' + n, badgeShow: '👀 Покажи код учителю — он добавит баллы к тесту' },
      coins: { title: 'Монеты «Твоя школа»', titleN: (n) => (n * 5) + ' ' + pluralRu(n * 5, ['монета', 'монеты', 'монет']) + ' «Твоя школа»', desc: 'Обменяй жетоны на монеты: 1 🎟 = 5 монет', how: 'Настоящий обмен: переведи жетоны в монеты приложения «Твоя школа» — их тратят на реальные покупки в школьном магазине. 1 жетон = 5 монет. Выбираешь, сколько жетонов обменять, — получишь код, покажи учителю, чтобы он начислил монеты.', chooseHelp: (bal) => '1 жетон = 5 монет «Твоя школа». У тебя ' + bal + ' 🎟. Выбери, сколько обменять.', chooseBig: (n) => (n * 5) + ' монет', badgeShow: '👀 Покажи код учителю — он начислит монеты в «Твоя школа»' },
    },
    voice: {
      homeIdle: ['{name}, серия ждёт. Не сливайся 😎', '{name}, твой ход. 1 раунд — погнали.', '{name}, один раунд — и ты в деле.', 'Ну что, {name}, докажем?'],
      homeDone: ['Цель закрыта, {name}. Но кто сказал стоп? 😏', '{name}, день взят. Ещё круг?', '{name}, норма закрыта. Добавки? 😏'],
      high: ['{score}, {name}. Чисто 😎', '{name}, красиво. Слабо все 15? 😉', 'Сильно, {name}. Так держать.', '{score} — {name} в ударе 🔥'],
      mid: ['{score}, {name}. Норм, но ты можешь чище.', 'Идём, {name}. Дожми в следующем.', '{name}, крепко. Ещё чуть-чуть — и чисто.'],
      low: ['{name}, это не твой потолок. Реванш?', 'Бывает, {name}. Разбор уже помог — погнали ещё.', '{name}, не считается. Ещё раунд — и покажем класс.'],
      hero: ['{name} — ГЕРОЙ. Весь пак твой 🦸', 'Полный пак, {name}. Уважение 🤝', '{name}, пак собран целиком. Красава 🦸'],
      celHero: ['Весь пак за один заход, {name}. Это уровень 🦸', '{name}, ты взял(а) весь пак. Огонь!', 'Грамматика, словообразование, письмо — всё твоё, {name}.'],
      celLevel: ['Растёшь на глазах, {name}. Дальше — выше!', 'Новая ступень взята, {name}. Так и надо 💪', '{name}, уровень апнут. ОГЭ всё ближе.'],
      celStreak: ['Привычка побеждать, {name}. Не отпускай 🔥', '{name}, столько дней подряд — характер!', 'Каждый день в деле, {name}. Это и есть результат.'],
      celFreeze: ['Заморозка в кармане, {name}. Один пропуск теперь не страшен 🧊', '{name}, серия под защитой. Можно выдохнуть.'],
      celAch: ['Новое достижение, {name}! Коллекция растёт 🏅', '{name}, есть новая ачивка. Так держать!', 'Ещё один значок твой, {name}. Красиво.'],
    },
  },

  en: {
    // splash
    brandline: 'Speak & Smile · EGE Trainer',
    greetHi: "Hi! I'm Speaky 👋", greetQ: "What's your name?",
    namePlaceholder: 'Your name', go: "Let's go!",
    offlineNote: 'Everything works offline. Your progress stays on your device — no accounts.',
    // nav
    navHome: 'Home', navProgress: 'Progress', navRewards: 'Rewards',
    // home
    welcomeBack: 'Welcome back', today: 'Today', week: 'This week', lvl: 'Lv.',
    toRank: (r, n) => `to "${r}": ${n} XP`, maxRank: 'top rank reached',
    empty: 'nothing yet',
    goalTitle: 'Daily goal', goalDone: (s) => `Done for today — ${s}`, goalIdle: 'Do at least one round',
    packTitle: '🦸 Weekly pack', packOf: (n, tot) => `${n} of ${tot}`,
    packNote: 'Finish a round in every section — collect all and become a Hero',
    sectionsTitle: 'Sections', myProgress: 'My progress', rewards: 'Rewards',
    soonTitle: 'Reading · Listening', soonMeta: 'coming in the next update', soon: 'Soon',
    soonScreenTitle: 'Coming soon', soonScreenText: 'This section is under development — it will appear in a future update.',
    // reading
    reading: {
      pick: 'Choose a task type',
      tfTitle: 'True · False · Not stated', tfSub: '28 texts · 7 statements each',
      matchTitle: 'Text ↔ question', matchSub: '38 tasks · texts A–F',
      readFirst: 'Read the text and judge each statement',
      matchInstr: 'Match each text A–F to the right question',
      questionsTitle: 'Questions',
      tf: ['True', 'False', 'Not stated'],
      pickQ: '—',
      correctNum: (n) => 'Correct: ' + n,
      nextText: 'Another text',
      why: 'Why', evidenceLabel: 'In the text',
      notStatedNote: 'This is not mentioned in the text.',
    },
    readingEge: {
      pick: 'Choose a task type',
      headingsTitle: 'Match the headings', headingsSub: '56 tasks · 7 texts ↔ 8 headings',
      gapsTitle: 'Gapped text', gapsSub: '57 tasks · insert the missing parts',
      mcTitle: 'Multiple choice', mcSub: '51 texts · several questions each',
      headingsInstr: 'Match each text (A–G) to a heading. One heading is extra.',
      gapsInstr: 'Fill each gap (A–F) with the right part. One part is extra.',
      mcInstr: 'Read the text and choose the best answer for each question.',
      headingsLabel: 'Headings', partsLabel: 'Parts', questionsTitle: 'Questions',
      readFirst: 'Read carefully',
      pickN: '—',
      correctNum: (n) => 'Correct: ' + n,
      nextText: 'Another task',
      why: 'Why',
    },
    vocab: {
      sub: 'Theme of the week · 15 words a day',
      dailyTitle: 'Daily goal',
      dailyDone: (g) => `Daily goal done — ${g} words 🎉`,
      dailyLeft: (c, g) => `${c} of ${g} words today`,
      startDaily: 'Practise words',
      practiceMore: 'More cards',
      dueNote: (n, w) => `${n} ${w} to review`,
      dueNone: 'New words from this week\'s theme',
      learning: 'Theme of the week: ',
      learningSub: 'New words come from here; review is mixed',
      pickTheme: 'Choose the theme of the week',
      searchPlaceholder: 'Search a word or phrase…',
      searchEmpty: 'Nothing found',
      searchCount: (n) => `${n} found`,
      searchTitle: 'Dictionary', searchBtn: 'Dictionary',
      learnedOf: (a, b) => `learned ${a} of ${b}`,
      inProgress: (n) => `${n} in progress`,
      tapToFlip: 'Tap to see the translation',
      dontKnow: "Don't know",
      know: 'I know it',
      dayClosed: 'Daily vocabulary goal done! 🎉',
      keepGoing: 'Keep going!',
      toThemes: 'Themes',
    },
    // drill
    loadingTasks: 'Loading tasks…', allTopics: 'All topics',
    allTopicsSub: 'A random round of 15 tasks', byCodifier: 'Topics',
    mistakes: 'Practice your mistakes', mistakesSub: (n, w) => `${n} ${w} to review`,
    tasksWord: ['task', 'tasks', 'tasks'], roundsWord: ['round', 'rounds', 'rounds'], streakLabel: 'streak',
    topicsWord: ['topic', 'topics', 'topics'], whyCorrect: 'Correct!', whyCheck: 'Compare with the correct answer above.',
    enterAnswer: 'Type your answer', check: 'Check', next: 'Next', finish: 'Finish round',
    why: 'Why', correctIs: (k) => 'Correct answer: ' + k, baseWord: 'Word given',
    more15: '15 more', otherTopic: 'Other topic', toHome: 'Home',
    rStreak: 'Streak', rXp: 'XP', rPack: 'Pack', rFreeze: 'Freeze', freezeSaved: 'saved your streak',
    dayWord: (s) => s === 1 ? 'day' : 'days',
    praiseHigh: 'great pace!', praiseMid: 'good job', praiseLow: 'keep practising',
    accLine: (acc, praise) => `${acc}% correct · ${praise}`,
    // writing (ЕГЭ — два задания, тексты общие)
    wLoading: 'Loading writing tasks…', wPickSub: 'Pick a task and write your answer',
    wLetterFrom: (n) => 'Email from ' + n, wFrom: (n) => 'From ' + n,
    wCheck: 'Check my writing', wRecheck: 'Check again',
    wVerdictDefault: 'Checked against the official criteria.',
    wErrorsTitle: 'Fixes: before → after', wCorrectedTitle: 'Corrected version',
    wMyWorks: 'My writing', wWorksSub: (n) => `${n} saved`,
    wWorksEmpty: 'Your checked writing will appear here — come back to re-read it before the exam.',
    wYourText: 'Your answer', wTaskPrompt: 'Task',
    wWords: (n, w) => `${n} ${w}`, wordsWord: ['word', 'words', 'words'],
    wErrShort: 'Write your answer first (at least a few sentences).',
    wErrServer: (s) => 'Check failed: ' + s,
    // progress
    progTitle: 'My progress', bySection: 'By section',
    solved: (a, c) => `done ${a} · correct ${c}`, noSolved: 'no tasks solved yet',
    avgTitle: 'Average writing score', avgSub: (n) => `essays checked: ${n}`, avgCrit: 'by the official criteria',
    achTitle: 'Achievements', changeName: 'Change name', reset: 'Reset',
    resetConfirm: 'Reset all progress on this device?',
    soundOn: '🔊 Sound: on', soundOff: '🔇 Sound: off',
    heroWord: ['hero', 'heroes', 'heroes'],
    // rewards / perks
    tokensLabel: (n, w) => `${w} earned`, tokenWord: ['token', 'tokens', 'tokens'],
    perksSub: 'Perks from your teacher. Get a badge and show it in class.',
    skinsTitle: 'XP bar skins', redeemedTitle: 'Used',
    skinEquipped: 'On', skinEquip: 'Equip',
    skinOn: '✅ Equipped now', skinOpen: '✅ Unlocked', perkEnough: '✅ Enough tokens', perkNeed: (n) => '🎟 ' + n + ' more needed',
    levelsTitle: 'Levels & ranks', levelsHow: 'XP builds up as you study: +10 for every correct answer, +30 for a perfect round (no mistakes). More XP — higher rank. Your level is highlighted.',
    ptsSpend: (n) => 'Spends: ' + n + ' 🎟', ptsRedeem: 'Redeem', perkChoose: 'Choose',
    // Онбординг: дата экзамена
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    examWhenTitle: (exam) => 'When is your ' + exam + '?',
    examWhenSub: 'I will put a countdown on the home screen. You can change the date later.',
    examMonthLabel: 'Month', examYearLabel: 'Year', examNext: 'Next →', examSkip: "Don't know yet",
    // Счётчик
    countdownTitle: 'Until the exam',
    countdownFuture: (w, exam) => '≈ ' + w + (w === 1 ? ' week' : ' weeks') + ' until ' + exam,
    countdownDays: (d, exam) => d + (d === 1 ? ' day' : ' days') + ' until ' + exam,
    countdownThisMonth: (exam) => exam + ' is this month 💪',
    countdownSetTitle: 'When is the exam?',
    countdownSetPrompt: 'Set the date — I will start a countdown',
    // Weekly study plan
    planCardTitle: 'Weekly plan',
    planToCover: (n) => '~' + n + (n === 1 ? ' task' : ' tasks') + ' a week',
    planPerDay: (m) => '≈ ' + m + ' a day',
    planMiniSec: (name, n) => name + ' ' + n,
    planCardSub: 'to master everything by the exam',
    planMinCardSub: "can't cover it all — keeping a minimum",
    planMinShort: (n) => 'minimum ~' + n + '/wk: all topics + words',
    planDoneCard: 'All done! 🎉 Keep reviewing.',
    planTitle: 'Study plan',
    planWeeksLeft: (w) => w + (w === 1 ? ' week' : ' weeks') + ' until the exam',
    planSummary: (n, m) => '~' + n + ' tasks a week · ≈ ' + m + ' a day',
    planMinBanner: 'Not enough time to master everything. First do EVERY topic at least 5 tasks and keep 15 words a day — that covers all topics. Time left — push topics to a crown.',
    planSecLine: (done, tot) => 'mastered ' + done + ' of ' + tot + ' topics',
    planSecRem: (r, w) => '~' + r + ' · ' + w + '/wk',
    planSecDone: '✅ all mastered',
    planTopicsHdr: 'What is left by topic',
    planTopicLeft: (k) => k + ' left',
    planVocabTitle: 'Vocabulary',
    planVocabLine: (l, tot) => '15 words/day · mastered ' + l + ' of ' + tot,
    planAllDone: 'Whole bank done — great job! Keep reviewing weak topics.',
    readFmt: { '1.3.1': 'Headings', '1.3.2': 'Gapped text', '1.3.3': 'Multiple choice' },
    planGoals: {
      full: { name: 'Whole bank', desc: 'solve every question' },
      master: { name: 'Master all topics', desc: 'every topic to a crown' },
      light: { name: 'All topics once', desc: 'a quick pass over topics' },
    },
    planMark: { ok: '✅', tight: '⚠️', hard: '🔒', done: '🎉' },
    planMarkText: { ok: 'doable', tight: 'intense', hard: "won't fit", done: 'done' },
    planChooseHdr: 'Your goal',
    planRecommended: 'recommended',
    planGoalCardSub: (name, day) => name + ' · ' + day,
    planHardHint: "Not reachable at the usual pace in the time left — pick an easier goal or push harder.",
    // Советы (для ЕГЭ контента пока нет, memosFile=null → не используется)
    tipsTitle: (sec) => sec + ' · Speaky tips',
    tipFormat: '📋 Format', tipTime: '⏱ Time', tipHow: '✅ How to do it', tipMistakes: '⚠️ Common mistakes',
    examIntro: [
      { img: './assets/spiky-talk.png', title: 'What is the EGE', text: 'The English EGE has two parts.\nWritten (~3h10m): listening, reading, grammar & vocabulary, writing.\nSpeaking (~17 min) — a separate part.\nMax 100 points: 22 to pass, 40+ for university.' },
      { img: './assets/spiky-check.png', title: 'Written part', text: 'Four sections, you manage the time yourself:\n1) Listening (~30 min).\n2) Reading (~30 min).\n3) Grammar & vocabulary (~15 min).\n4) Writing — 2 tasks (~50 min).' },
      { img: './assets/spiky-idea.png', title: 'Writing — two tasks', text: 'Task 37 — an email to a pen-friend: answer all questions AND ask 3 of your own (~100 words).\nTask 38 — an opinion text based on a chart, with 6 aspects (~200–250 words).\nMiss an aspect or a question and you lose points.' },
      { img: './assets/spiky-thumb.png', title: "It's all about practice", text: "Here you'll train every section: grammar, vocabulary, reading, email and essay.\nIn each section Speaky shows how to do the task and the time to spend.\nLet's go! 💪" },
    ],
    rewSub: 'XP bar skins. Unlocked by levels and heroes you collect.',
    badgeShow: '👀 Show this screen to your teacher', badgeDone: 'Done',
    // celebration moments
    celHeroT: 'HERO!', celLevelT: (lvl, t) => 'Level ' + lvl + ' · ' + t,
    celStreakT: (n) => n + ' days in a row!', celFreezeT: 'Freeze earned',
    celTokenT: (n, w) => '+' + n + ' ' + w, celTokenText: (name) => `A token for you, ${name}. Trade it for a perk with your teacher 🎟`,
    celAchText: (desc, phrase) => 'Achievement: ' + desc + '. ' + phrase,
    celNext: 'Next →', celClaim: 'Claim!',
    achGot: '✅ Earned', achLocked: '🔒 Not yet', modalClose: 'Got it',
    friend: 'friend',
    sections: { vocab: 'Topic Vocabulary', grammar: 'Grammar', wordform: 'Word formation', reading: 'Reading', writing: 'Writing', speaking: 'Speaking', lexis: 'Vocabulary', email: 'Email', essay: 'Essay' },
    sectionMeta: { vocab: 'theme of the week · 15 words a day', grammar: '389 tasks · grammar', wordform: '728 tasks · word forms', reading: '469 tasks · 3 formats', writing: 'writing', speaking: 'soon', lexis: '728 tasks · vocabulary', email: 'task 37 · K1–K3', essay: 'task 38 · K1–K5' },
    ranks: ['Rookie', 'Trainee', 'Skilled', 'Pro', 'Master', 'Legend'],
    skins: {
      aurora: { name: 'Aurora', desc: 'Purple → honey', need: 'available now', how: 'A skin is the colour of your XP bar at the top. "Aurora" (purple → honey) is available right away — equip it in one tap.' },
      sunset: { name: 'Sunset', desc: 'Berry → orange', need: 'Level 2', how: 'A skin colours your XP bar. "Sunset" (berry → orange) unlocks at level 2 — earn XP for correct answers.' },
      grape: { name: 'Grape', desc: 'Deep purple', need: 'Level 4', how: 'A skin colours your XP bar. "Grape" (deep purple) unlocks at level 4.' },
      honeycomb: { name: 'Honey', desc: 'Warm honey', need: '2 heroes', how: 'A skin colours your XP bar. "Honey" unlocks once you become a Hero twice (collect the pack twice).' },
      guru: { name: 'Guru', desc: 'Full S&S spectrum', need: 'Reach "Legend"', how: 'A skin colours your XP bar. "Guru" (the full Speak & Smile spectrum) unlocks at the top rank "Legend" — level 6.' },
    },
    ach: {
      first: { title: 'First step', desc: 'First round', how: 'Finish your very first round and earn your first XP. Every journey starts here!' },
      perfect: { title: 'Perfect', desc: 'A perfect round', how: 'Finish a whole round without a single mistake. A perfect round also earns you a streak freeze.', rep: (n) => 'Perfect rounds: ' + n + ' · +' + n + ' 🧊' },
      hero: { title: 'Hero', desc: 'Collect the pack', how: 'Complete the whole weekly pack — clear every section for the period. A pack earns a 🎟 token for a teacher perk.', rep: (n) => 'Packs collected: ' + n + ' · +' + n + ' 🎟' },
      hundred: { title: 'Century', desc: '100 tasks solved', how: 'Solve 100 tasks in total, across any sections. The counter adds up by itself.' },
      week: { title: 'On a roll', desc: '7-day streak', how: 'Study 7 days in a row — push your streak 🔥 to seven. Hit your daily vocab goal each day to keep it growing. Reach 7/14/30/50/100 for +2 🎟; break it and climb back and you earn them again.', rep: (n) => 'Your best streak: ' + n + ' days' },
      gold: { title: 'Topic master', desc: 'A gold crown', how: 'Take any topic all the way to a gold crown 👑 — lots of solved tasks at high accuracy.', rep: (n) => 'Gold crowns: ' + n },
      fivehundred: { title: 'Five hundred', desc: '500 tasks solved', how: 'Solve 500 tasks in total. That is real volume — serious progress.' },
      frosty: { title: 'Stocked up', desc: '3 freezes saved', how: 'Save up 3 streak freezes 🧊 (one for each perfect round). A freeze covers a missed day.' },
    },
    perks: {
      hint: { title: 'Hint on a test', desc: 'One hint during a test', how: 'A real perk from your teacher: one hint during a test. Costs 2 🎟. Redeem it for a code and show it to your teacher. Tokens come from completed packs (Hero) and streak milestones.' },
      nohw: { title: 'No-homework pass', desc: 'Come to class with no homework', how: 'A real perk: come to class with no homework. Costs 4 🎟. Redeem for a code to show your teacher. Earn tokens from packs and streaks.' },
      points: { title: 'Test bonus points', titleN: (n) => '+' + n + (n === 1 ? ' point' : ' points') + ' on a test', desc: 'Trade tokens for points: 1 🎟 = +1 point', how: 'A real bonus from your teacher: add points to your test result. 1 token = +1 point, from 1 to 10 per test (as many tokens as you have). Choose how many to spend — get a "+N points" code to show your teacher.', chooseHelp: (bal) => '1 token = +1 test point. You have ' + bal + ' 🎟. Choose how many to add (up to 10).', chooseBig: (n) => '+' + n, badgeShow: '👀 Show the code to your teacher — they add the test points' },
      coins: { title: '"Your School" coins', titleN: (n) => (n * 5) + ' "Your School" coins', desc: 'Trade tokens for coins: 1 🎟 = 5 coins', how: 'A real exchange: turn tokens into coins in the "Your School" app — spend them on real purchases in the school store. 1 token = 5 coins. Choose how many tokens to exchange — get a code, show it to your teacher to credit the coins.', chooseHelp: (bal) => '1 token = 5 "Your School" coins. You have ' + bal + ' 🎟. Choose how many to exchange.', chooseBig: (n) => (n * 5) + ' coins', badgeShow: '👀 Show the code to your teacher — they credit "Your School" coins' },
    },
    voice: {
      homeIdle: ['{name}, your streak is waiting. Keep it up 😎', '{name}, your move. One round — go.', '{name}, one round and you are in.', 'So, {name}, shall we?'],
      homeDone: ["Goal done, {name}. But who said stop? 😏", '{name}, day done. One more?', '{name}, target hit. More? 😏'],
      high: ['{score}, {name}. Clean 😎', '{name}, nice. All 15 next time? 😉', 'Strong, {name}. Keep going.', '{score} — {name} is on fire 🔥'],
      mid: ['{score}, {name}. Good, but you can do cleaner.', 'Keep going, {name}. Nail the next one.', '{name}, solid. Almost perfect.'],
      low: ['{name}, that is not your limit. Rematch?', 'It happens, {name}. The review helped — go again.', "{name}, doesn't count. One more round and show your best."],
      hero: ['{name} — HERO. The whole pack is yours 🦸', 'Full pack, {name}. Respect 🤝', '{name}, full pack collected. Nice 🦸'],
      celHero: ['The whole pack in one go, {name}. That is a level 🦸', '{name}, you took the whole pack. Fire!', 'Grammar, vocabulary, writing — all yours, {name}.'],
      celLevel: ['You are growing fast, {name}. Onwards and upwards!', 'New level reached, {name}. That is the way 💪', '{name}, level up. The exam is closer.'],
      celStreak: ['A winning habit, {name}. Hold on 🔥', '{name}, so many days in a row — character!', 'Every day in action, {name}. That is the result.'],
      celFreeze: ['A freeze in your pocket, {name}. One missed day is fine now 🧊', '{name}, your streak is protected. Relax.'],
      celAch: ['New achievement, {name}! Your collection grows 🏅', '{name}, a new badge. Keep it up!', 'One more badge is yours, {name}. Nice.'],
    },
  },
};
